const articleContent = {
  '/marchingBandWhereExcellenceAndSuccessUnite': {
    category: 'Band Life', title: 'Look Again: Who Are Those Band Members on the Field?',
    dek: 'You are watching much more than a marching band. Take another look at the people turning hundreds of individual decisions into one effortless performance.',
    heroImage: '/images/articles/article-title-bgs/whos-who-on-marchingband.png', readingTime: '6 min read',
    sections: [
      { type: 'paragraph', text: "In a few minutes, they'll be moving across the turf while remembering music, drill, counts, spacing, entrances, dynamics, choreography, equipment changes—and probably a dozen corrections made during their last rehearsal. They'll be listening to one another, watching the drum major, controlling their breathing, remembering where they're going, and trying to make several hundred individual decisions look like one effortless performance." },
      { type: 'paragraph', text: "That's impressive enough. But more than forty years of research has revealed a remarkable picture of who these musicians are, where they're going, and what many of them will accomplish long after tonight's final note." },
      { type: 'heading', text: "First, They're Pretty Smart" },
      { type: 'paragraph', text: 'Playing an instrument requires the brain to perform an extraordinary number of tasks simultaneously. Reading music, interpreting rhythm, controlling fine motor movements, listening critically, responding emotionally, and coordinating with others all happen at the same time. Marching band adds one more complication: you have to do all of that while remembering where you are supposed to be standing.' },
      { type: 'statGrid', items: [['92.2%', 'high-school graduation rate'], ['93.9%', 'attendance rate'], ['87.6%', 'rank in the top ten percent of their class'], ['46.4%', 'pursue graduate or advanced study']] },
      { type: 'heading', text: 'Band Builds More Than Musicians' },
      { type: 'paragraph', text: 'Watch a marching band closely and you quickly realize that individual talent is not enough. Every band member depends upon someone else. That creates an unusual culture of responsibility: discipline, teamwork, cooperation, accountability, and the ability to work with people whose backgrounds and experiences may be very different from their own.' },
      { type: 'pullQuote', text: 'While directors may think they are teaching notes, rhythms, drill, and technique, something much larger may be happening.' },
      { type: 'heading', text: 'And Then They Go to College' },
      { type: 'paragraph', text: "The story becomes even more interesting after high school. Band members are finding ways to pay for college, many continue performing, and some pursue music as a career. The trumpet player you are watching tonight may become an engineer and still play in a university marching band. The percussionist may major in computer science and never stop performing." },
      { type: 'heading', text: 'Now Look at the Field One More Time' },
      { type: 'paragraph', text: "In a moment, another band will enter. You will see the uniforms and hear the announcer. Look again at the people on the field. You may be watching future physicians, engineers, teachers, attorneys, scientists, entrepreneurs, researchers, performers, and business leaders. They are just wearing matching uniforms tonight." },
    ],
  },
  '/symphonyOfAspirations': {
    category: 'Performance', title: 'The Day I Knew I Had to Be in That Band',
    dek: 'One Saturday in Columbia, one state championship, and the beginning of a lifelong love of marching band.',
    heroImage: '/images/articles/article-title-bgs/the-day-I-knew.png', readingTime: '8 min read',
    sections: [
      { type: 'paragraph', text: 'I was eleven years old, living in Greenville, South Carolina, and had been playing the clarinet for exactly seven weeks. I could hardly be considered an accomplished musician, but I was already fascinated by band.' },
      { type: 'paragraph', text: 'My friend Brad was an eighth-grader and a very good trumpet player. One day, he invited me to go with his family to the South Carolina Band Directors Association State Marching Band Contest in Columbia. I did not know it then, but that invitation would change my life.' },
      { type: 'heading', text: 'The Day Began Before Sunrise' },
      { type: 'paragraph', text: 'The night before the contest, Brad’s family packed enough food to survive several weeks without civilization: cheese biscuits, party mix, egg-salad sandwiches, baked ham, pepper and onion dip, and sausage-and-cheese balls. His father loaded a charcoal grill into the station wagon. I had never been to a marching-band contest before, so I did not know whether this was normal.' },
      { type: 'pullQuote', text: 'By the end of the day, tailgating would be permanently embedded in my vocabulary.' },
      { type: 'heading', text: 'They Cheered for Everybody' },
      { type: 'paragraph', text: 'Every band that entered the field was greeted with applause. It did not matter where they were from. People cheered. Occasionally, the Parker fans around me became especially enthusiastic about another band, and an older booster explained that some of those bands were directed by former Parker Band members.' },
      { type: 'paragraph', text: '“We are so very proud of them,” she said. That stayed with me. These people were not simply proud of their own band. They were proud of people who had once been part of their band and carried that experience somewhere else.' },
      { type: 'heading', text: 'A Family Larger Than One School' },
      { type: 'paragraph', text: 'Even at eleven years old, I understood that I was seeing something much bigger than a school activity. I was seeing a family. And right then, a thought began forming in my mind: I wanted to belong to this.' },
      { type: 'heading', text: 'The First Note' },
      { type: 'paragraph', text: 'The contest taught me that marching band was not only about winning trophies. It was about preparation, belonging, tradition, food in a parking lot, and people who continued to support one another years after they had left the field.' },
      { type: 'pullQuote', text: 'Sometimes a lifelong musical journey begins with a single invitation.' },
    ],
  },
  '/harmonizingHearts': {
    category: 'Band Life', title: 'You’re Part of the Show, Too',
    dek: 'The best marching-band contests do not happen only on the field. They come alive because the audience knows how to listen, react, and make room for every performer.',
    heroImage: "/images/articles/article-title-bgs/you're-part-of-the-show.png", readingTime: '6 min read',
    sections: [
      { type: 'paragraph', text: "One of the best things about a marching-band contest isn't happening on the field. It's happening in the stands: parents, grandparents, former band members, directors, friends, and fans who drove three hours because somebody they love is marching tonight." },
      { type: 'paragraph', text: 'Put them all together and you get one of the great traditions of marching band: the audience. A great audience can make a stadium come alive, and you do not have to know anyone in a band to cheer for them.' },
      { type: 'heading', text: "Your Band Isn't the Only Band" },
      { type: 'paragraph', text: "Naturally, you're going to cheer loudest for your own band. You should. That's part of the fun. But every band that takes the field has rehearsed, memorized, marched, sweated, loaded trucks, and performed in front of thousands of people. That deserves respect." },
      { type: 'paragraph', text: "Cheer for the great moments. Applaud the effort. When another band finishes its show, give those band members the recognition they've earned. You do not have to want them to beat your band. You just have to appreciate what they did." },
      { type: 'heading', text: 'When a Band Performs, They Own the Stadium' },
      { type: 'paragraph', text: "Once a band begins performing, they own those next several minutes. Conversations can wait. Phone calls can wait. The concession stand can wait. The rest of the day can wait too. The band only gets one performance. Give it to them." },
      { type: 'heading', text: 'The Rules of the Stands' },
      { type: 'paragraph', text: "Being a great marching-band audience member isn't complicated. Silence your phone, keep conversations for the breaks, take calls somewhere else, keep aisles and views clear, and plan bathroom or concession trips between bands whenever possible." },
      { type: 'paragraph', text: "Never make negative comments about another band within earshot of its families, supporters, or performers. Never boo. If you have questions about scoring, save them for later instead of approaching judges or contest officials." },
      { type: 'heading', text: 'Watch What You Say' },
      { type: 'paragraph', text: "The person sitting directly behind you might be the mother of the trumpet player you just criticized. The person beside you might be that band's former director. A show may be entertainment to you, but for someone nearby those eight or ten minutes may represent months of work by someone they love." },
      { type: 'heading', text: 'Never Boo a Marching Band' },
      { type: 'pullQuote', text: 'Marching-band audiences can be passionate without becoming hostile.' },
      { type: 'paragraph', text: "You may disagree with a score or feel disappointed by a placement. Discuss it later. But when bands are standing on the field awaiting results, give every one of them the dignity and respect they have earned." },
      { type: 'heading', text: 'A Great Audience Can Change a Performance' },
      { type: 'paragraph', text: 'A band reaches the biggest moment in its show. The sound builds, the drill opens, the color guard reaches the impact, and suddenly thousands of people respond together. An audience cannot change the notes or the drill, but it can change the energy in the stadium.' },
      { type: 'heading', text: 'The Audience Matters' },
      { type: 'paragraph', text: "Cheer for your band. Celebrate every great moment. Give every band its moment, give every performance your attention, respect the people around you, and thank the volunteers and sponsors who made the contest possible. The audience is part of the experience too." },
    ],
  },
  '/MarchingBandsUnveilingTheRhythmOfStyle': {
    category: 'Design & Performance', title: 'Why Do Marching Bands Look So Different?',
    dek: 'From military precision to theatrical corps style, every band brings its own personality to the field.',
    heroImage: '/images/articles/article-title-bgs/marchingbands-look-so-different.png', readingTime: '7 min read',
    sections: [
      { type: 'paragraph', text: 'Watch several bands at the same contest and you may start wondering: how can they all be marching bands and look so completely different? One band marches in perfectly straight lines. The next surrounds the field with props, electronics, dancers, and scenery. Another enters with high steps, powerful brass, and enough energy to move the entire stadium.' },
      { type: 'paragraph', text: "That's because marching band doesn't have just one style. It has traditions that have developed, crossed paths, borrowed from one another, and created the variety we see on marching fields today." },
      { type: 'heading', text: "Style Is the Band's Personality" },
      { type: 'paragraph', text: 'Think about style as the personality of a marching band. It affects how the band moves, what music it performs, how formations are created, how the color guard is used, whether props or electronics are part of the production, and how the audience is expected to experience the show.' },
      { type: 'heading', text: 'Military Style: Precision Above All' },
      { type: 'paragraph', text: 'Military-style marching is one of the foundations of the tradition. Straight lines, uniform spacing, consistent step sizes, sharp turns, disciplined posture, and tremendous attention to precision create an unmistakable visual impression.' },
      { type: 'paragraph', text: "The excitement comes from seeing a large group move with extraordinary uniformity. Everybody moves together, turns together, and arrives together. That's the show." },
      { type: 'heading', text: 'Corps Style: The Field Becomes a Stage' },
      { type: 'paragraph', text: 'Corps-style marching asks a different question: how can we tell this story? Music and visual design are built around one another through lines, curves, blocks, circles, scatter formations, rapid transitions, and large geometric pictures.' },
      { type: 'paragraph', text: 'Band members may march forward, backward, and sideways. They may run, dance, move individually, and suddenly reconnect into a massive formation. Increasingly, the entire field becomes part of the production.' },
      { type: 'heading', text: 'Everything Can Become Part of the Story' },
      { type: 'paragraph', text: 'Platforms, backdrops, rolling structures, fabric, costume changes, keyboards, sound effects, amplification, narration, soloists, and elaborate props can all become part of the visual storytelling. The result can feel extraordinarily theatrical.' },
      { type: 'heading', text: 'Show Style: Entertain the Crowd' },
      { type: 'paragraph', text: 'Show-style bands place entertainment front and center. Recognizable music, bold formations, dance, high-energy movement, and audience interaction combine to put on a show. HBCU marching bands have developed one of America’s most distinctive traditions through powerful brass, driving percussion, high-step movement, dance, showmanship, and contemporary music.' },
      { type: 'heading', text: 'Parade Style and Scatter Bands' },
      { type: 'paragraph', text: 'Parade bands develop skills for continuous forward motion, endurance, carriage, spacing, uniformity, and sound. Scatter bands take a deliberately unconventional route, using scramble formations, humor, scripts, jokes, satire, and unexpected movement.' },
      { type: 'heading', text: 'Modern Competition Is Often a Blend' },
      { type: 'paragraph', text: 'Today’s designers borrow ideas from everywhere. A straight line may be perfect for one musical moment, a giant curve for another, and a dance movement may communicate something drill cannot. The styles have not disappeared; they have become ingredients.' },
      { type: 'heading', text: 'Now Watch the Next Band Differently' },
      { type: 'paragraph', text: 'When the next band takes the field, watch how they move. Are the formations precise? Is the band telling a story? Is the emphasis entertainment? Are there props, electronics, dance, traditional marches, or contemporary music? Start noticing those decisions and you begin seeing design, not just notes and drill.' },
      { type: 'pullQuote', text: "That's marching band. They've all got style." },
    ],
  },
  '/MarchingBandAFusion': {
    category: 'Band Life', title: 'Is Marching Band a Sport—or Something More?',
    dek: 'It requires athletic preparation, artistic judgment, teamwork, and the ability to perform under pressure. The label is less important than what band members actually do.',
    heroImage: '/images/articles/article-title-bgs/is-marchingband-a-sport.png', readingTime: '6 min read',
    sections: [
      { type: 'paragraph', text: 'Marching band asks performers to move, play, remember, react, and recover at the same time. A single production can demand endurance, strength, coordination, flexibility, precision, and sustained concentration.' },
      { type: 'heading', text: 'The Athletic Part Is Real' },
      { type: 'paragraph', text: 'Band members rehearse for hours, often outdoors and in difficult weather. They carry instruments and equipment, learn demanding movement, and repeat sections until the body can perform accurately even when tired.' },
      { type: 'heading', text: 'But It Is Also an Art Form' },
      { type: 'paragraph', text: 'The goal is not simply to move quickly or cover distance. Performers interpret music, communicate an idea, shape visual moments, and make creative decisions as an ensemble. Athletic ability supports the performance; it does not replace artistry.' },
      { type: 'heading', text: 'The Work Happens as a Team' },
      { type: 'paragraph', text: 'Marching band has no room for isolated success. Each performer depends on the timing, spacing, sound, and commitment of everyone nearby. That shared responsibility is one of the clearest reasons the activity feels like both competition and community.' },
      { type: 'heading', text: 'So What Should We Call It?' },
      { type: 'paragraph', text: 'Sport, performance art, or something more complete: marching band combines physical preparation with musical and visual expression. The useful question is not whether it fits one label. The useful question is whether we recognize the extraordinary work happening on the field.' },
      { type: 'pullQuote', text: 'Marching band is what happens when athletic discipline and artistic purpose meet.' },
    ],
  },
  '/nextSaturday': {
    category: 'Family & Future', title: 'The Saturday After: The Last Contest',
    dek: 'After months of rehearsals, travel, performances, and routine, the quiet weekend can feel surprisingly unfamiliar. Here is how families can help the transition feel purposeful.',
    heroImage: '/images/articles/article-title-bgs/saturday-after.png', readingTime: '6 min read',
    sections: [
      { type: 'paragraph', text: 'For months, Saturday had a rhythm: early alarms, packed food, uniforms, buses, warmups, performances, awards, and the long ride home. Then one Saturday arrives and there is nowhere to be.' },
      { type: 'heading', text: 'The Quiet Can Feel Strange' },
      { type: 'paragraph', text: 'A season-ending performance can bring pride and relief, but it can also leave a real gap. Band members lose a daily source of structure, friends, challenge, and shared purpose all at once.' },
      { type: 'heading', text: 'Let the Season Land' },
      { type: 'paragraph', text: 'Give them time to be tired. Talk about what they enjoyed, what was difficult, and what they learned. The first conversation does not need to become a plan for the next activity.' },
      { type: 'heading', text: 'Keep the Community Close' },
      { type: 'paragraph', text: 'The relationships built during a season do not have to end with the final competition. A meal, concert, alumni event, or simple check-in can help preserve the sense of belonging that made the season meaningful.' },
      { type: 'heading', text: 'Turn Reflection into Direction' },
      { type: 'paragraph', text: 'Later, ask what they want to carry forward: stronger musicianship, better fitness, leadership, a new ensemble, college opportunities, or simply the confidence that comes from finishing something difficult.' },
      { type: 'pullQuote', text: 'The season ends on the calendar before it ends in the person who lived it.' },
    ],
  },
  '/marchingToSuccess': {
    category: 'College & Scholarships', title: 'Could Marching Band Help Pay for College?',
    dek: 'The answer can be yes—but families need to understand what scholarships cover, how auditions work, and what questions to ask before making a plan.',
    heroImage: '/images/articles/article-title-bgs/marchingband-pay-for-college.png', readingTime: '7 min read',
    sections: [
      { type: 'paragraph', text: 'For many families, marching band is first a place to belong. But the discipline, musicianship, leadership, and performance experience developed there can also open doors to college.' },
      { type: 'heading', text: 'Start with the Right Question' },
      { type: 'paragraph', text: 'Do not ask only whether a college offers a marching-band scholarship. Ask what the award covers, whether it is renewable, what participation is required, and how it fits with academic and financial-aid packages.' },
      { type: 'heading', text: 'There Is More Than One Path' },
      { type: 'paragraph', text: 'Opportunities may come through the marching band, concert ensembles, music departments, leadership programs, academic achievement, or outside scholarships connected to performance and service.' },
      { type: 'heading', text: 'Auditions Are About Preparation' },
      { type: 'paragraph', text: 'Students should learn the repertoire, practice sight-reading, prepare scales or excerpts when requested, and understand the schedule before audition day. A strong musical foundation matters more than trying to sound impressive at the last minute.' },
      { type: 'heading', text: 'Build the Story Behind the Music' },
      { type: 'paragraph', text: 'A student’s profile can include performances, leadership, service, teaching, videos, honors, and the persistence shown through years of rehearsal. Colleges are evaluating a person, not just a single audition.' },
      { type: 'heading', text: 'Ask Before You Commit' },
      { type: 'paragraph', text: 'Compare the full cost, renewal terms, rehearsal expectations, travel, academic support, and ensemble culture. The best opportunity is one that supports the student’s education and long-term goals.' },
      { type: 'pullQuote', text: 'A marching-band opportunity can help pay for college, but the best decision begins with good questions.' },
    ],
  },
  '/crackingTheCode': {
    category: 'Competition', title: 'How Did the Judges Get That Score?',
    dek: 'Marching-band scores can seem mysterious from the stands. A little context makes the numbers easier to understand—and the performance more interesting to watch.',
    heroImage: '/images/articles/article-title-bgs/how-did-the-judges-get-the-score.png', readingTime: '7 min read',
    sections: [
      { type: 'paragraph', text: 'When the scores are announced, fans often compare totals before they have had a chance to understand what the judges were evaluating. The score is not a single opinion. It is the result of several captions, criteria, and observations.' },
      { type: 'heading', text: 'Judges Evaluate What the Band Presents' },
      { type: 'paragraph', text: 'Depending on the organization, judges may consider music performance, music analysis, visual performance, visual analysis, effect, achievement, and other categories. The names and weighting can vary.' },
      { type: 'heading', text: 'Difficulty Is Not the Same as Success' },
      { type: 'paragraph', text: 'A difficult musical passage or demanding visual moment creates an opportunity, not an automatic reward. The ensemble has to communicate the idea and achieve it with clarity.' },
      { type: 'heading', text: 'Achievement Matters' },
      { type: 'paragraph', text: 'Judges listen and watch for consistency, timing, balance, control, clarity, and the relationship between intention and result. Small details can matter because they reveal how completely a band has mastered its program.' },
      { type: 'heading', text: 'The Audience Sees One Show' },
      { type: 'paragraph', text: 'A judge may be listening to one section while observing another, writing notes, and comparing the performance to a published rubric. That does not make the score infallible, but it explains why a moment that feels enormous to the crowd may not determine the final number by itself.' },
      { type: 'heading', text: 'Watch for the Design' },
      { type: 'paragraph', text: 'The next time you watch a band, notice what the program is asking them to do, how successfully they do it, and how the music, movement, and visual effect work together. You may still debate the score, but you will understand more of the work behind it.' },
      { type: 'pullQuote', text: 'A score is a snapshot of a performance through a particular judging system—not the entire story of a band.' },
    ],
  },
  '/aSymphonyOfSupport': {
    category: 'Family & Community', title: 'Behind Every Great Marching Band Are Some Remarkable Parents',
    titleLines: ['Behind Every', 'Great Marching Band', 'Are Some Remarkable Parents'],
    dek: 'The audience sees the performance. Families often see the early mornings, logistics, sacrifices, and quiet encouragement that make it possible.',
    heroImage: '/images/articles/article-title-bgs/remarkable-parents.png', readingTime: '6 min read',
    sections: [
      { type: 'paragraph', text: 'Before a band steps onto the field, somebody has packed food, checked the uniform, found the missing item, handled transportation, and reminded a tired student that the work is worth finishing.' },
      { type: 'heading', text: 'The Work Nobody Sees' },
      { type: 'paragraph', text: 'Parents and guardians may coordinate schedules, wash uniforms, volunteer at events, drive to rehearsals, organize fundraisers, and help students recover after long days. Much of that work happens quietly and repeatedly.' },
      { type: 'heading', text: 'Support Is More Than Logistics' },
      { type: 'paragraph', text: 'The most important support may be emotional: listening after a difficult rehearsal, helping a student put criticism into perspective, celebrating progress, and creating enough calm for the performer to keep learning.' },
      { type: 'heading', text: 'Let Them Own the Experience' },
      { type: 'paragraph', text: 'Helpful support does not mean solving every problem. Students need room to manage equipment, communicate with directors, prepare for auditions, and learn from setbacks. Guidance works best when it builds independence.' },
      { type: 'heading', text: 'A Community Effort' },
      { type: 'paragraph', text: 'No family does this alone. Directors, staff, boosters, volunteers, alumni, and other families create the network that keeps a program moving. That network becomes part of what students remember long after the season ends.' },
      { type: 'pullQuote', text: 'The performance lasts eight minutes. The support behind it lasts all season—and often much longer.' },
    ],
  },
  '/marchingContests': {
    category: 'Competition', title: 'More Than a Trophy: Why Marching Band Contests Matter',
    titleLines: ['More Than a Trophy:', 'Why Marching Band Contests Matter'],
    dek: 'Competition gives a season direction, but its deeper value is found in preparation, community, feedback, and the shared experience of taking the field.',
    heroImage: '/images/articles/article-title-bgs/morethan-a-trophy.png', readingTime: '6 min read',
    sections: [
      { type: 'paragraph', text: 'A contest is easy to describe as a ranking: one band places first, another second, and another goes home without a trophy. But that view misses most of what happens before, during, and after the announcement.' },
      { type: 'heading', text: 'A Deadline Gives the Work Shape' },
      { type: 'paragraph', text: 'The next contest gives students a reason to refine a transition, clean a phrase, fix a spacing issue, or strengthen a difficult passage. The deadline turns daily practice into visible progress.' },
      { type: 'heading', text: 'The Field Creates Perspective' },
      { type: 'paragraph', text: 'Seeing other programs expands a student’s idea of what marching band can be. Bands bring different traditions, resources, design choices, and communities to the same field.' },
      { type: 'heading', text: 'Feedback Can Travel Home' },
      { type: 'paragraph', text: 'A score sheet or judge’s comment can give directors and students a useful outside perspective. It can point toward the next rehearsal without reducing the entire program to a number.' },
      { type: 'heading', text: 'The Community Is Part of the Result' },
      { type: 'paragraph', text: 'Contests connect families, alumni, volunteers, sponsors, and fans. They create memories in parking lots and stands as much as on the field.' },
      { type: 'heading', text: 'The Trophy Is Not the Whole Story' },
      { type: 'paragraph', text: 'Winning can be thrilling. So can a cleaner performance, a stronger final chord, a student finding confidence, or a band finishing a season together. Those outcomes do not always fit on an awards table.' },
      { type: 'pullQuote', text: 'A contest measures a performance. It does not measure the full value of the people who created it.' },
    ],
  },
  '/evolutionOfMarchingBandUniforms': {
    category: 'History & Design', title: 'Why Do Marching Band Uniforms Look the Way They Do?',
    dek: 'Marching-band uniforms carry military history, school identity, practical demands, and the visual language of the performance all at once.',
    heroImage: '/images/evolution.jpeg', readingTime: '7 min read',
    sections: [
      { type: 'paragraph', text: 'Marching bands did not invent the idea of a uniform from nothing. Their clothing grew from military and civic traditions in which coordinated dress communicated discipline, belonging, and public purpose.' },
      { type: 'heading', text: 'Military Roots and Early History' },
      { type: 'paragraph', text: 'Early bands used uniforms that reflected military formality: structured jackets, bright colors, hats, braids, and insignia. The clothing helped distinguish the ensemble and made movement readable from a distance.' },
      { type: 'heading', text: 'Uniforms Became School Identity' },
      { type: 'paragraph', text: 'As school marching bands grew, uniforms began carrying school colors, symbols, traditions, and regional identity. A band’s appearance could make a community recognizable before the first note sounded.' },
      { type: 'heading', text: 'Performance Changed the Design' },
      { type: 'paragraph', text: 'Modern shows ask performers to move in more varied ways and sometimes use costume changes, removable layers, dramatic color, or softer silhouettes. A uniform is now part of the production design, not only a symbol of membership.' },
      { type: 'heading', text: 'Form Must Follow Function' },
      { type: 'paragraph', text: 'The best uniform still has to work. It must allow movement, protect the performer, handle weather, support instrument technique, and survive a demanding season. Visual impact matters, but comfort and durability matter too.' },
      { type: 'heading', text: 'Look at the Next Band Differently' },
      { type: 'paragraph', text: 'Notice the silhouette, color, headwear, details, and how the uniform changes the way formations read. The clothing is telling you something about the band’s history, identity, and design choices before the performance is over.' },
      { type: 'pullQuote', text: 'A marching-band uniform is history you can see, adapted for a performance that is happening now.' },
    ],
  },
  '/historyOfMarchingBands': {
    category: 'History', title: 'History of Marching Bands',
    dek: 'The story of marching bands is a story of military tradition, school spirit, changing music, and communities finding a way to move together.',
    heroImage: '/images/homb-home.jpeg', readingTime: '8 min read',
    sections: [
      { type: 'paragraph', text: 'Long before marching bands filled football fields, musicians used drums, horns, and fifes to communicate across distance. Sound gave groups a shared signal, a shared pace, and a way to gather.' },
      { type: 'heading', text: 'From Military Signals to Public Performance' },
      { type: 'paragraph', text: 'Military ensembles shaped the early visual language of marching: uniforms, formations, cadence, and ceremony. Over time, those traditions moved into parades, civic events, universities, and schools.' },
      { type: 'heading', text: 'Schools Made the Tradition Their Own' },
      { type: 'paragraph', text: 'School bands connected music with identity. Colors, fight songs, halftime performances, and community celebrations gave students a visible way to represent where they came from.' },
      { type: 'heading', text: 'Competition Changed the Field' },
      { type: 'paragraph', text: 'As contests developed, bands began refining musical achievement, visual design, precision, and effect. Different regions and organizations built different traditions, which is why no single marching style tells the whole story.' },
      { type: 'heading', text: 'The Tradition Keeps Moving' },
      { type: 'paragraph', text: 'Today’s bands may combine military precision, corps-style design, show-band energy, electronics, dance, and theatrical storytelling. The history is not finished; every season adds another chapter.' },
      { type: 'pullQuote', text: 'Every marching band carries the past forward while creating something its own.' },
    ],
  },
  '/winnersOfThePast': {
    category: 'People & Culture', title: 'Celebrities in Marching Band',
    dek: 'Before the stage, screen, studio, or spotlight, many successful people learned something valuable by showing up for band.',
    heroImage: '/images/articles/article-title-bgs/celebrities.png', readingTime: '6 min read',
    sections: [
      { type: 'paragraph', text: 'A marching-band background does not guarantee fame, but it can develop habits that travel well: preparation, listening, timing, confidence, teamwork, and the ability to perform when people are watching.' },
      { type: 'heading', text: 'The Skills Travel Beyond the Field' },
      { type: 'paragraph', text: 'Performers learn to manage nerves, respond to direction, support an ensemble, and keep going after a mistake. Those skills matter whether the next stage is a concert hall, a recording studio, a film set, or a completely different profession.' },
      { type: 'heading', text: 'Band Is a Starting Point, Not a Limit' },
      { type: 'paragraph', text: 'Some former band members continue as professional musicians. Others become actors, educators, athletes, entrepreneurs, and leaders. The activity gives them practice in commitment without dictating the destination.' },
      { type: 'heading', text: 'Watch the Preparation' },
      { type: 'paragraph', text: 'When a public figure brings musical confidence, stage presence, or an instinct for ensemble timing to a new setting, there may be an earlier chapter behind it: years spent learning how to contribute to a band.' },
      { type: 'pullQuote', text: 'The field may be where the audience first notices the performance, but the lessons continue long after the uniform comes off.' },
    ],
  },
  '/marchingBandJokes': {
    category: 'Between Performances', title: 'Marching Band Jokes',
    dek: 'Because after a long rehearsal, a difficult rep, and one more “one more time,” sometimes the only reasonable response is to laugh.',
    heroImage: '/images/articles/article-title-bgs/bandjokes.png', readingTime: '4 min read',
    sections: [
      { type: 'paragraph', text: 'Marching band takes discipline seriously. Marching-band people, thankfully, do not always take themselves seriously.' },
      { type: 'heading', text: 'The Rehearsal Classics' },
      { type: 'paragraph', text: '“One more time” is a phrase that can mean one more repetition, one more hour, or one more reason to check the weather. A rehearsal is not finished until the staff says it is finished—and sometimes not even then.' },
      { type: 'heading', text: 'The Field-Tested Truths' },
      { type: 'paragraph', text: 'If you cannot find your dot, stand still and look confident. If the uniform feels comfortable, you probably forgot something. If everyone is early, check the schedule again.' },
      { type: 'heading', text: 'Share the Laugh' },
      { type: 'paragraph', text: 'The best band jokes come from shared experience: long bus rides, mysterious counts, snack breaks, instrument accidents, and the moment an entire ensemble realizes it has been marching the wrong direction together.' },
      { type: 'pullQuote', text: 'A good marching-band joke is like a clean ensemble entrance: better when everyone gets it at the same time.' },
    ],
  },
  '/recipes': {
    kind: 'recipes',
    category: 'Tailgate', title: 'Tailgating Recipes',
    dek: 'The contest-day menu is part of the tradition: food that travels well, feeds a crowd, and makes the hours between performances feel like an event of their own.',
    heroImage: '/images/articles/article-title-bgs/tail-gate.png', readingTime: '5 min read',
    sections: [
      { type: 'paragraph', text: 'A marching-band contest can begin before sunrise and end long after the final awards. That is why experienced families plan the food as carefully as they plan the uniforms and equipment.' },
      { type: 'heading', text: 'Good Tailgate Food Has a Job' },
      { type: 'paragraph', text: 'The best recipes are easy to transport, simple to serve, generous enough for a group, and satisfying without making the next performance feel impossible.' },
      { type: 'heading', text: 'Build a Table People Remember' },
      { type: 'paragraph', text: 'Cheese biscuits, party mix, egg-salad sandwiches, baked ham, pepper-and-onion dip, sausage-and-cheese balls, grilled favorites, and something sweet can turn a parking lot into a gathering place.' },
      { type: 'heading', text: 'The Meal Is Part of the Memory' },
      { type: 'paragraph', text: 'Years later, people may remember the score. They also remember who brought the grill, which table had the best dip, and how the whole group gathered between performances.' },
      { type: 'pullQuote', text: 'At a marching-band contest, the parking lot can be part kitchen, part reunion, and part opening ceremony.' },
    ],
  },
  '/whosWhoOnTheMarchingBandField': {
    category: 'Band Life', title: "Who's Who on the Marching Band Field?",
    dek: 'A modern marching band is several groups working together to create one production. Here is your guide to the people you see before the first note.',
    heroImage: '/images/who-are-these.jpg', readingTime: '6 min read',
    sections: [
      { type: 'paragraph', text: 'The next band is getting ready. Some people carry trumpets, some wear drums, others push marimbas, and someone is rolling a giant wall toward the 50-yard line. Above them, a drum major raises a hand from a podium.' },
      { type: 'heading', text: 'The Drum Majors' },
      { type: 'paragraph', text: 'Drum majors establish tempo, cue entrances and releases, communicate changes, and provide a visual reference for performers spread across an enormous field. Their visible conducting is only part of their responsibility.' },
      { type: 'heading', text: 'The Sections' },
      { type: 'paragraph', text: 'Brass, woodwinds, battery percussion, front ensemble, and color guard each contribute a distinct part of the production. The show works when those parts listen and respond to one another.' },
      { type: 'heading', text: 'The People Behind the Show' },
      { type: 'paragraph', text: 'Directors, designers, technicians, volunteers, and support crews help turn rehearsal into performance. The field is the visible result of a much larger team.' },
      { type: 'pullQuote', text: 'When you know who is on the field, you start seeing the performance as a collaboration instead of a crowd.' },
    ],
  },
  '/whatHappensBeforeABandTakesTheField': {
    category: 'Behind the Scenes', title: 'What Happens Before a Band Takes the Field?',
    dek: 'By the time a marching band reaches the stadium, it may already have been working for hours.',
    heroImage: '/images/marching-contests-small.jpeg', readingTime: '6 min read',
    sections: [
      { type: 'paragraph', text: 'You hear a snare drum in the distance, then brass, then the same eight measures played again and again. Somewhere beyond the stands, a band is preparing for the performance you are waiting to see.' },
      { type: 'heading', text: 'It Starts with the Buses' },
      { type: 'paragraph', text: 'Equipment, uniforms, food, water, props, and hundreds of people have to arrive, unload, organize, and move through a schedule before the audience sees the first formation.' },
      { type: 'heading', text: 'Warmups Build the Performance' },
      { type: 'paragraph', text: 'Musicians warm up individually and in sections. The ensemble checks tone, balance, articulation, and timing. Visual groups review movement, equipment, and the details that make the production safe and clear.' },
      { type: 'heading', text: 'The Last Minutes Matter' },
      { type: 'paragraph', text: 'Uniforms go on, props are staged, the band receives final reminders, and the group gathers its focus. The audience may see a calm entrance; the performers know how much preparation is underneath it.' },
      { type: 'pullQuote', text: 'The performance begins long before the band crosses the sideline.' },
    ],
  },
  '/fromMarchingBandToMilitaryBand': {
    category: 'Music Careers', title: 'From Marching Band to a United States Military Band',
    dek: 'A professional military music career is a path many families never consider—and it can begin with the musicianship developed on a marching-band field.',
    heroImage: '/images/is-it-a-sport.jpg', readingTime: '7 min read',
    sections: [
      { type: 'paragraph', text: 'Among the recruiters and information tables at a contest, families may encounter another possibility for a talented musician: professional performance in a United States military band.' },
      { type: 'heading', text: 'Yes, Military Music Is a Real Career' },
      { type: 'paragraph', text: 'Military musicians perform at ceremonies, public concerts, parades, patriotic events, educational programs, official functions, and events representing the United States at home and abroad.' },
      { type: 'heading', text: 'The Audition Is Serious' },
      { type: 'paragraph', text: 'Candidates should research the branch, musical requirements, audition process, service obligation, and available assignments. A general recruiter can explain military service, but music personnel can explain what it takes to win a musical position.' },
      { type: 'heading', text: 'Start by Becoming a Better Musician' },
      { type: 'paragraph', text: 'Private lessons, sight-reading, tone development, scales, solos, concert band, jazz ensemble, honor-band opportunities, recordings, and listening to outstanding players all build useful preparation.' },
      { type: 'heading', text: 'Make an Informed Decision' },
      { type: 'paragraph', text: 'Exploring a military music career is different from making a military commitment. Ask questions, compare branches, understand the requirements, and make sure the musician understands both words in “military musician.”' },
      { type: 'pullQuote', text: 'For some musicians, the journey from marching band to military band becomes a profession, a commitment, and a way to keep making music while serving their country.' },
    ],
  },
  '/whyAreTheBandsInDifferentClasses': {
    category: 'Competition', title: 'Why Are the Bands in Different Classes?',
    dek: 'Classifications organize a competition, but they do not tell you how good a band is—or how meaningful its performance will be.',
    heroImage: '/images/homb-home.jpeg', readingTime: '7 min read',
    sections: [
      { type: 'paragraph', text: 'One band takes the field with 58 members. The next has 217. Then the announcer says “Class 3A,” and you wonder how anyone decided that.' },
      { type: 'heading', text: 'There Is No National Classification System' },
      { type: 'paragraph', text: 'Different states, circuits, associations, and contests classify bands differently. Some use the number of performers, some use school enrollment, and others use a combination of factors.' },
      { type: 'heading', text: 'Sometimes It Is Band Size' },
      { type: 'paragraph', text: 'Grouping smaller ensembles with smaller ensembles and larger ensembles with larger ensembles can create a useful comparison. The exact ranges and definitions vary.' },
      { type: 'heading', text: 'Sometimes It Is School Enrollment' },
      { type: 'paragraph', text: 'A school with 2,000 students may be placed in a large-school classification even if only 75 performers take the field. Another contest may classify the same band by its actual size.' },
      { type: 'heading', text: 'Class Does Not Mean Quality' },
      { type: 'paragraph', text: 'A higher class does not automatically mean a better band, and a lower class does not mean a weaker band. Size creates possibilities, but it does not guarantee excellence.' },
      { type: 'heading', text: 'Ask a Better Question' },
      { type: 'paragraph', text: 'Instead of asking why a band is in one class, ask how much it is accomplishing with the band it has. That question reveals the performance more clearly than a label ever can.' },
      { type: 'pullQuote', text: 'Classifications organize the competition. They do not determine the performance.' },
    ],
  },
};

export default articleContent;
