const featuredPersonalities = [
  {
    name: 'Dolly Parton',
    played: 'Drums and Majorette',
    school: 'Sevier County High School · Sevierville, Tennessee',
    knownFor: 'Country Music Artist, Businesswoman, Philanthropist',
    image: '/images/articles/article-content-pics/celebrities/5.png',
    alt: 'Dolly Parton performing',
  },
  {
    name: 'Lizzo',
    fullName: 'Melissa Viviane Jefferson',
    played: 'Flute, Piccolo, and French Horn',
    school: 'Alief Elsik High School · Houston, Texas',
    knownFor: 'Singer, Songwriter, Rapper, Actress',
    image: '/images/articles/article-content-pics/celebrities/1.png',
    alt: 'Lizzo playing flute',
  },
  {
    name: 'Jennifer Garner',
    played: 'Saxophone',
    school: 'George Washington High School · Charleston, West Virginia',
    knownFor: 'Actor, Film Producer, Spokesperson',
    image: '/images/articles/article-content-pics/celebrities/2.png',
    alt: 'Jennifer Garner playing saxophone',
  },
  {
    name: 'Vince Carter',
    played: 'Euphonium and Drum Major',
    school: 'Mainland High School · Daytona Beach, Florida',
    knownFor: 'Basketball Player',
    image: '/images/articles/article-content-pics/celebrities/3.png',
    alt: 'Vince Carter in a basketball jersey',
  },
  {
    name: 'Bill Clinton',
    played: 'Saxophone and Drum Major',
    school: 'Hot Springs High School · Hot Springs, Arkansas',
    knownFor: '42nd President of the United States',
    image: '/images/articles/article-content-pics/celebrities/4.png',
    alt: 'Bill Clinton in a suit',
  },
  {
    name: 'Julia Roberts',
    played: 'Oboe',
    school: 'Campbell High School · Smyrna, Georgia',
    knownFor: 'Actress',
    image: '/images/articles/article-content-pics/celebrities/6.png',
    alt: 'Julia Roberts with her oboe',
  },
  {
    name: 'Jimmy Kimmel',
    played: 'Clarinet',
    school: 'Ed W. Clark High School · Las Vegas, Nevada',
    knownFor: 'Television Host',
    image: '/images/articles/article-content-pics/celebrities/7.png',
    alt: 'Jimmy Kimmel with his clarinet',
  },
  {
    name: 'Aretha Franklin',
    played: 'Tuba',
    school: 'Northern High School · Detroit, Michigan',
    knownFor: 'Singer-Songwriter, Record Producer, Civil-Rights Activist',
    image: '/images/articles/article-content-pics/celebrities/8.png',
    alt: 'Aretha Franklin smiling',
  },
  {
    name: 'Neil Armstrong',
    played: 'Euphonium',
    school: 'Blume High School · Wapakoneta, Ohio',
    knownFor: 'Astronaut and First Person to Walk on the Moon',
    image: '/images/articles/article-content-pics/celebrities/9.png',
    alt: 'Neil Armstrong in uniform',
  },
  {
    name: 'Samuel L. Jackson',
    played: 'Trumpet, Piccolo, and French Horn',
    school: 'Riverside High School · Chattanooga, Tennessee',
    knownFor: 'Actor, Director, Civil-Rights Activist',
    image: '/images/articles/article-content-pics/celebrities/10.png',
    alt: 'Young Samuel L. Jackson',
  },
  {
    name: 'Amanda Seyfried',
    played: 'Clarinet',
    school: 'William Allen High School · Allentown, Pennsylvania',
    knownFor: 'Actress, Singer',
    image: '/images/articles/article-content-pics/celebrities/11.png',
    alt: 'Amanda Seyfried',
  },
  {
    name: 'Vanessa Williams',
    played: 'French Horn, Piano, Violin',
    school: 'Horace Greeley High School · Chappaqua, New York',
    knownFor: 'Singer, Actress, Broadway Performer',
    image: '/images/articles/article-content-pics/celebrities/12.png',
    alt: 'Vanessa Williams',
  },
  {
    name: 'Steven Spielberg',
    played: 'Clarinet',
    school: 'Saratoga High School · Saratoga, California',
    knownFor: 'Film Director, Producer, Screenwriter',
    image: '/images/articles/article-content-pics/celebrities/13.png',
    alt: 'Steven Spielberg',
  },
  {
    name: 'Ewan McGregor',
    played: 'French Horn, Drums',
    school: 'Morrison’s Academy · Crieff, Scotland',
    knownFor: 'Actor, Singer, Director',
    image: '/images/articles/article-content-pics/celebrities/14.png',
    alt: 'Ewan McGregor',
  },
];

const notableBySection = [
  ['Flute', 'Alanis Morissette · Halle Berry · Celine Dion · Terry Crews · Calista Flockhart · George Eastman · Alyssa Milano · Noah Webster · Gwen Stefani · Tina Fey · Molly Erdman · James Wolfensohn · Knute Rockne · Oscar Robertson · Patrick Henry · John Quincy Adams · Sarah Palin'],
  ['Oboe', "Julia Roberts · Dennis O'Hare"],
  ['Clarinet', 'Rainn Wilson · Woody Allen · Gloria Estefan · Tony Shalhoub · Eva Longoria · Michael DeBakey · Allan Greenspan · Steven Spielberg · Robert Reid · Amy Acuff'],
  ['Bass clarinet', 'Zakk Wylde · George Segal'],
  ['Saxophone', 'Allan Greenspan · Roy Williams · David Robinson · Fred MacMurray · Tedy Bruschi · Bob Hope · Lionel Richie · Tyler Wright · Tom Selleck · Richard Gere · Ronald McNair · Robert Ryman'],
  ['Trumpet', 'James Woods · John Glenn · Michael Anthony · Drew Carey · Kesha · Steven Tyler · Prince Charles · Montel Williams · Peter Weller · Steve Earle · Shania Twain · Flea · Jackie Gleason · Eric Lindros · Brandon Routh · Samuel L. Jackson'],
  ['French horn', 'Ewan McGregor · Vanessa Williams · Otto Graham · Henry Cisneros · Samuel L. Jackson'],
  ['Trombone', 'Jonathan Frakes · Bill Engvall · Nelly Furtado · Conrad Janis · Bobby Bowden · John Pankow · Tony Stewart · Fred Rogers'],
  ['Baritone', 'Neil Armstrong'],
  ['Tuba', 'Andy Griffith · Malik Rose · Thomas F. Wilson · Harry Smith · Dan Aykroyd · Aretha Franklin'],
  ['Percussion', 'Mike Anderson · Tommy Lee · Adam Brody · Tracy Simien · Johnny Depp · Eddie George · Trent Reznor · Dana Carvey · Vinnie Paul · Walter Payton · Johnny Carson · Mike Piazza · Emeril Lagasse · Rosie O’Donnell'],
];

export default {
  '/winnersOfThePast': {
    kind: 'celebrities',
    category: 'People & Culture',
    title: 'Celebrities in Marching Band',
    dek: 'The Impact of Marching Bands on Icons of Success',
    heroImage: '/images/articles/article-title-bgs/celebrities.png',
    readingTime: '6 min read',
    intro: 'Marching bands have left an indelible mark on the lives of many remarkable individuals. The rhythmic cadence of drums, the blend of brass and woodwinds, and the precision of synchronized movement can shape the way people show up long after high school.',
    featuredPersonalities,
    notableBySection,
    closing: 'As we look back on the legendary figures who once stood on the same turf as today’s students, a shared path becomes clear. Discipline, teamwork, creativity, and perseverance travel well—and the next remarkable story may already be marching across the field.',
  },
};
