const fullArticleContent = {
  '/MarchingBandAFusion': {
    category: 'Band Life',
    title: 'Is Marching Band a Sport—or Something More?',
    dek: '',
    heroImage: '/images/articles/article-title-bgs/is-marchingband-a-sport.png',
    readingTime: '6 min read',
    sections: [
      {"type":"paragraph","text":"You've probably heard the debate."},
      {"type":"paragraph","text":"Is marching band a sport?"},
      {"type":"paragraph","text":"Ask a football player and you may get one answer."},
      {"type":"paragraph","text":"Ask a band member who just spent ten hours rehearsing in August heat while carrying a forty-pound instrument and you may get another."},
      {"type":"paragraph","text":"But while you're sitting here at a marching band contest, take a look at what's actually happening on the field."},
      {"type":"paragraph","text":"Band members are marching."},
      {"type":"paragraph","text":"Running."},
      {"type":"paragraph","text":"Changing direction."},
      {"type":"paragraph","text":"Controlling their breathing."},
      {"type":"paragraph","text":"Carrying instruments."},
      {"type":"paragraph","text":"Remembering hundreds of movements."},
      {"type":"paragraph","text":"Playing music."},
      {"type":"paragraph","text":"Performing choreography."},
      {"type":"paragraph","text":"Watching a drum major."},
      {"type":"paragraph","text":"Listening to one another."},
      {"type":"paragraph","text":"And doing all of it while an audience and a panel of judges watch every move."},
      {"type":"paragraph","text":"So, is marching band a sport?"},
      {"type":"paragraph","text":"Yes."},
      {"type":"paragraph","text":"But that's really only the beginning of the answer."},
      {"type":"paragraph","text":"By Most Definitions, It Qualifies"},
      {"type":"paragraph","text":"Look at the traditional definitions of sport and certain words appear again and again:"},
      {"type":"paragraph","text":"Physical exertion."},
      {"type":"paragraph","text":"Skill."},
      {"type":"paragraph","text":"Competition."},
      {"type":"paragraph","text":"Rules."},
      {"type":"paragraph","text":"Training."},
      {"type":"paragraph","text":"Performance."},
      {"type":"paragraph","text":"Marching band checks every one of those boxes."},
      {"type":"paragraph","text":"Competitive marching bands train for months."},
      {"type":"paragraph","text":"They compete against other bands."},
      {"type":"paragraph","text":"Their performances are evaluated under established rules."},
      {"type":"paragraph","text":"Band members develop physical endurance, coordination, balance, strength, and control."},
      {"type":"paragraph","text":"And championships are determined by performance."},
      {"type":"paragraph","text":"That sounds remarkably similar to a sport."},
      {"type":"paragraph","text":"But something is still missing."},
      {"type":"paragraph","text":"These Band Members Are Athletes"},
      {"type":"paragraph","text":"Spend one day at band camp and the athletic argument becomes considerably easier to understand."},
      {"type":"paragraph","text":"Band members may rehearse for hours outdoors."},
      {"type":"paragraph","text":"They march forward."},
      {"type":"paragraph","text":"They march backward."},
      {"type":"paragraph","text":"They move sideways."},
      {"type":"paragraph","text":"They change step sizes."},
      {"type":"paragraph","text":"They lunge."},
      {"type":"paragraph","text":"They run."},
      {"type":"paragraph","text":"They dance."},
      {"type":"paragraph","text":"And they do it repeatedly."},
      {"type":"paragraph","text":"Now add an instrument."},
      {"type":"paragraph","text":"Some are relatively light."},
      {"type":"paragraph","text":"Others most definitely are not."},
      {"type":"paragraph","text":"Marching percussion, tubas, sousaphones, and other large instruments place substantial physical demands on the people carrying them."},
      {"type":"paragraph","text":"Then add heat."},
      {"type":"paragraph","text":"Uniforms."},
      {"type":"paragraph","text":"Long rehearsals."},
      {"type":"paragraph","text":"And performances during which there are no time-outs because somebody is tired."},
      {"type":"paragraph","text":"Marching band requires endurance."},
      {"type":"paragraph","text":"There's really no getting around it."},
      {"type":"paragraph","text":"But They're Doing Something Most Athletes Aren't"},
      {"type":"paragraph","text":"Here's where marching band becomes different."},
      {"type":"paragraph","text":"Band members aren't simply moving."},
      {"type":"paragraph","text":"They're making music while they move."},
      {"type":"paragraph","text":"Every note still has to be correct."},
      {"type":"paragraph","text":"Every entrance matters."},
      {"type":"paragraph","text":"Every release matters."},
      {"type":"paragraph","text":"Every articulation matters."},
      {"type":"paragraph","text":"Tone quality matters."},
      {"type":"paragraph","text":"Balance matters."},
      {"type":"paragraph","text":"Intonation matters."},
      {"type":"paragraph","text":"And breathing certainly matters."},
      {"type":"paragraph","text":"Imagine running across a field while trying to produce a beautiful musical phrase on a trumpet."},
      {"type":"paragraph","text":"Or playing a difficult clarinet passage while marching backward."},
      {"type":"paragraph","text":"Or maintaining a perfectly controlled roll on a snare drum while changing direction."},
      {"type":"paragraph","text":"The physical activity doesn't excuse the musical performance."},
      {"type":"paragraph","text":"The band member has to do both."},
      {"type":"paragraph","text":"At the same time."},
      {"type":"paragraph","text":"Then Add Hundreds of Places to Remember"},
      {"type":"paragraph","text":"A marching band member isn't simply told:"},
      {"type":"paragraph","text":"Go over there."},
      {"type":"paragraph","text":"Modern marching shows may require band members to memorize an extraordinary number of locations and transitions."},
      {"type":"paragraph","text":"Where am I?"},
      {"type":"paragraph","text":"Where am I going?"},
      {"type":"paragraph","text":"How many counts do I have to get there?"},
      {"type":"paragraph","text":"What's my step size?"},
      {"type":"paragraph","text":"Which direction am I facing?"},
      {"type":"paragraph","text":"Who should be beside me?"},
      {"type":"paragraph","text":"When does the next musical entrance occur?"},
      {"type":"paragraph","text":"And occasionally:"},
      {"type":"paragraph","text":"Why is that tuba coming directly toward me?"},
      {"type":"paragraph","text":"All of those decisions are happening while the band member is performing music."},
      {"type":"paragraph","text":"That combination of physical, musical, and mental demands is one of the things that makes marching band so unusual."},
      {"type":"paragraph","text":"Marching Band Is Also Performance Art"},
      {"type":"paragraph","text":"Now look beyond the athletic demands."},
      {"type":"paragraph","text":"Watch the next band enter the field."},
      {"type":"paragraph","text":"There's a theme."},
      {"type":"paragraph","text":"Costumes."},
      {"type":"paragraph","text":"Color."},
      {"type":"paragraph","text":"Movement."},
      {"type":"paragraph","text":"Music."},
      {"type":"paragraph","text":"Drama."},
      {"type":"paragraph","text":"Dance."},
      {"type":"paragraph","text":"Scenery."},
      {"type":"paragraph","text":"Props."},
      {"type":"paragraph","text":"Lighting effects at some events."},
      {"type":"paragraph","text":"Electronic sound."},
      {"type":"paragraph","text":"Perhaps narration."},
      {"type":"paragraph","text":"The color guard may portray characters or ideas."},
      {"type":"paragraph","text":"The music may tell a story."},
      {"type":"paragraph","text":"The drill may create images that disappear seconds later."},
      {"type":"paragraph","text":"The entire production has been designed to make you feel something."},
      {"type":"paragraph","text":"That isn't simply athletics."},
      {"type":"paragraph","text":"That's performance art."},
      {"type":"paragraph","text":"A modern marching show can sometimes resemble a theatrical production placed on a football field."},
      {"type":"paragraph","text":"The field becomes the stage."},
      {"type":"paragraph","text":"The band members become the performers."},
      {"type":"paragraph","text":"And you become the audience."},
      {"type":"paragraph","text":"And Yes, It's a Competition"},
      {"type":"paragraph","text":"Not every marching band competes."},
      {"type":"paragraph","text":"But the bands you're watching today probably do."},
      {"type":"paragraph","text":"And competition changes everything."},
      {"type":"paragraph","text":"Judges evaluate various aspects of the performance."},
      {"type":"paragraph","text":"Music."},
      {"type":"paragraph","text":"Visual achievement."},
      {"type":"paragraph","text":"Technique."},
      {"type":"paragraph","text":"Coordination."},
      {"type":"paragraph","text":"Effect."},
      {"type":"paragraph","text":"Percussion."},
      {"type":"paragraph","text":"Color guard."},
      {"type":"paragraph","text":"And other areas depending upon the competition."},
      {"type":"paragraph","text":"A championship isn't awarded because a band worked hard."},
      {"type":"paragraph","text":"Every band worked hard."},
      {"type":"paragraph","text":"It's awarded based upon what happens during those few minutes on the field."},
      {"type":"paragraph","text":"One performance."},
      {"type":"paragraph","text":"One opportunity."},
      {"type":"paragraph","text":"No replay tomorrow because the trumpet section had a bad night."},
      {"type":"paragraph","text":"That pressure is very real."},
      {"type":"paragraph","text":"And band members learn to perform through it."},
      {"type":"paragraph","text":"Nobody Wins Alone"},
      {"type":"paragraph","text":"Here's another similarity between marching band and team sports."},
      {"type":"paragraph","text":"No individual wins the contest."},
      {"type":"paragraph","text":"The best trumpet player can't do it."},
      {"type":"paragraph","text":"The drum major can't do it."},
      {"type":"paragraph","text":"The percussion section can't do it."},
      {"type":"paragraph","text":"The color guard can't do it."},
      {"type":"paragraph","text":"Everybody matters."},
      {"type":"paragraph","text":"One missed entrance changes a chord."},
      {"type":"paragraph","text":"One person arriving late changes a formation."},
      {"type":"paragraph","text":"One timing error can affect an entire visual moment."},
      {"type":"paragraph","text":"The band succeeds because hundreds of individual responsibilities come together at exactly the right time."},
      {"type":"paragraph","text":"That's teamwork in its purest form."},
      {"type":"paragraph","text":"So Why Isn't Marching Band Universally Called a Sport?"},
      {"type":"paragraph","text":"Part of the answer is tradition."},
      {"type":"paragraph","text":"Marching band generally lives within a school's music or fine arts program rather than its athletic department."},
      {"type":"paragraph","text":"Its history comes from music and military-band traditions."},
      {"type":"paragraph","text":"And although competitive marching has existed for generations, many people still know marching band primarily from football halftime performances and parades."},
      {"type":"paragraph","text":"So they see the instruments."},
      {"type":"paragraph","text":"They hear the music."},
      {"type":"paragraph","text":"They recognize the art."},
      {"type":"paragraph","text":"What they may not see are the hours of conditioning, movement training, repetition, physical preparation, and competition behind the performance."},
      {"type":"paragraph","text":"Context changes perception."},
      {"type":"paragraph","text":"Put an activity in an athletic arena and people tend to see athletics."},
      {"type":"paragraph","text":"Put it in the music department and people tend to see art."},
      {"type":"paragraph","text":"Marching band happens to be both."},
      {"type":"paragraph","text":"Maybe —Sport— Isn't a Big Enough Word"},
      {"type":"paragraph","text":"And that's where this old argument becomes interesting."},
      {"type":"paragraph","text":"Calling marching band a sport isn't wrong."},
      {"type":"paragraph","text":"It simply doesn't describe everything you're watching."},
      {"type":"paragraph","text":"Because marching band is also:"},
      {"type":"paragraph","text":"Music."},
      {"type":"paragraph","text":"Dance."},
      {"type":"paragraph","text":"Theatre."},
      {"type":"paragraph","text":"Visual design."},
      {"type":"paragraph","text":"Competition."},
      {"type":"paragraph","text":"Athletic movement."},
      {"type":"paragraph","text":"Pageantry."},
      {"type":"paragraph","text":"And teamwork."},
      {"type":"paragraph","text":"Very few activities ask young people to do all of those things simultaneously."},
      {"type":"paragraph","text":"Marching band does."},
      {"type":"paragraph","text":"Try This During the Next Performance"},
      {"type":"paragraph","text":"When the next band takes the field, watch one band member for a few seconds."},
      {"type":"paragraph","text":"Really watch."},
      {"type":"paragraph","text":"Notice the posture."},
      {"type":"paragraph","text":"The feet."},
      {"type":"paragraph","text":"The direction changes."},
      {"type":"paragraph","text":"The breathing."},
      {"type":"paragraph","text":"The instrument."},
      {"type":"paragraph","text":"The eyes moving between the field and the drum major."},
      {"type":"paragraph","text":"Then remember that the band member is also counting."},
      {"type":"paragraph","text":"Listening."},
      {"type":"paragraph","text":"Playing."},
      {"type":"paragraph","text":"Remembering drill."},
      {"type":"paragraph","text":"Responding to the people around them."},
      {"type":"paragraph","text":"And performing for you."},
      {"type":"paragraph","text":"Now imagine doing all of that while marching backward at a fast tempo."},
      {"type":"paragraph","text":"Suddenly the question isn't quite:"},
      {"type":"paragraph","text":"—Is marching band a sport?—"},
      {"type":"paragraph","text":"It becomes:"},
      {"type":"paragraph","text":"—How in the world are they doing all of this at once?—"},
      {"type":"paragraph","text":"So What's the Verdict?"},
      {"type":"paragraph","text":"Yes, marching band has the physical exertion, training, skill, rules, teamwork, and competition associated with sport."},
      {"type":"paragraph","text":"But it doesn't stop there."},
      {"type":"paragraph","text":"It's a sport."},
      {"type":"paragraph","text":"It's a concert."},
      {"type":"paragraph","text":"It's a theatrical production."},
      {"type":"paragraph","text":"It's a dance performance."},
      {"type":"paragraph","text":"It's a competition."},
      {"type":"paragraph","text":"It's a visual art form."},
      {"type":"paragraph","text":"And for the band members on the field, it's often a family."},
      {"type":"paragraph","text":"Maybe that's why the debate has lasted so long."},
      {"type":"paragraph","text":"We've been trying to fit marching band neatly into a category that isn't large enough to contain it."},
      {"type":"paragraph","text":"So while you're waiting for the next performance, forget about choosing between sport and art."},
      {"type":"paragraph","text":"When the next band takes the field, watch what those band members are actually being asked to do."},
      {"type":"paragraph","text":"Athletes move."},
      {"type":"paragraph","text":"Musicians play."},
      {"type":"paragraph","text":"Dancers perform."},
      {"type":"paragraph","text":"Actors communicate."},
      {"type":"paragraph","text":"Competitors compete."},
      {"type":"paragraph","text":"Marching band members do all of it."},
      {"type":"paragraph","text":"At the same time."},
      {"type":"paragraph","text":"And that may be the real definitive verdict:"},
      {"type":"paragraph","text":"Marching band isn't simply a sport or a performance art."},
      {"type":"paragraph","text":"It's something remarkable that happens when the two become one."},
    ],
  },
};

export default fullArticleContent;
