import type { OnTheBusArticle } from "./onTheBusArticleContent";

export const speakToYourselfContent: OnTheBusArticle = {
  title: "Speak to Yourself",
  sections: [
    { type: "paragraph", text: "The bus is moving, and almost everyone has something to say." },
    { type: "paragraph", text: "Someone behind you is laughing. Someone across the aisle is playing a video. Your friends are talking about another band, the weather, or whether there will be time to eat. A director is giving instructions. Somewhere, somebody is singing the same three lines over and over." },
    { type: "paragraph", text: "Usually, you might join in." },
    { type: "paragraph", text: "But today, you need a minute." },
    { type: "paragraph", text: "Maybe you are worried about the opening. Maybe yesterday’s rehearsal is still running through your mind. Maybe someone made a comment about your playing, your appearance, or whether you deserve your spot." },
    { type: "paragraph", text: "The words took only a second to say. They have been riding beside you ever since." },
    { type: "paragraph", text: "You cannot make the entire bus quiet. But you can begin to decide which voices receive your attention—and what you say to yourself when you turn inward." },
    { type: "heading", text: "You Are Allowed to Take a Quiet Minute" },
    { type: "paragraph", text: "Being part of a band does not mean you have to participate in every conversation." },
    { type: "paragraph", text: "You can enjoy your friends and still need a break from the noise. You can be excited about contest and still feel nervous. You can belong to this group without laughing at every joke or answering every question." },
    { type: "paragraph", text: "Try saying, “I’m going to take a quiet minute before we get there. I’ll talk with you in a little while.”" },
    { type: "paragraph", text: "You do not need a complicated explanation." },
    { type: "paragraph", text: "Keep listening for your director’s instructions and important announcements. If headphones are permitted, wait until those instructions are finished before using them, and keep the volume low enough to hear when you are needed." },
    { type: "paragraph", text: "A quiet minute is simply a little room to collect yourself." },
    { type: "heading", text: "Start With Where You Are" },
    { type: "paragraph", text: "Before you try to change your thoughts, notice your seat." },
    { type: "paragraph", text: "Feel your feet resting on the floor. Let your hands settle in your lap. Loosen your jaw and lower your shoulders." },
    { type: "paragraph", text: "Take an easy breath. Let it out slowly, without forcing it." },
    { type: "paragraph", text: "Look at something steady: your hands, the seat in front of you, or a small detail on your instrument case. You can keep your eyes open." },
    { type: "paragraph", text: "For a moment, you do not have to solve the whole day." },
    { type: "paragraph", text: "You are on a bus. You are sitting in a seat. You are traveling with people who have practiced alongside you." },
    { type: "paragraph", text: "The stadium is ahead. It does not need all your attention yet." },
    { type: "heading", text: "Notice What You Have Been Saying to Yourself" },
    { type: "paragraph", text: "Sometimes the loudest voice is the one nobody else can hear." },
    { type: "paragraph", text: "I’m going to mess up." },
    { type: "paragraph", text: "Everyone else is better prepared." },
    { type: "paragraph", text: "What if I let them down?" },
    { type: "paragraph", text: "Maybe that person was right about me." },
    { type: "paragraph", text: "Notice those thoughts without scolding yourself for having them. Being nervous does not make you weak, and having a discouraging thought does not make it true." },
    { type: "paragraph", text: "Ask yourself:" },
    { type: "paragraph", text: "Is this something I know, something I fear, or something someone said?" },
    { type: "paragraph", text: "There is a difference." },
    { type: "paragraph", text: "“I missed that entrance yesterday” describes something that happened." },
    { type: "paragraph", text: "“I will ruin the whole show” predicts something that has not happened." },
    { type: "paragraph", text: "One gives you a detail to work on. The other gives you a burden to carry." },
    { type: "heading", text: "Speak to Yourself Like Someone Worth Helping" },
    { type: "paragraph", text: "Think about what you would say to a friend who was sitting beside you, worried about performing." },
    { type: "paragraph", text: "Would you tell them they were hopeless? Would you remind them of every mistake they had ever made?" },
    { type: "paragraph", text: "Probably not." },
    { type: "paragraph", text: "You might say, “You’ve worked hard. You know more than you think. Take it one phrase at a time.”" },
    { type: "paragraph", text: "You deserve that kind of voice, too." },
    { type: "paragraph", text: "Speaking to yourself does not require a speech. You can say the words silently, whisper them, or write them in a note on your phone." },
    { type: "paragraph", text: "Choose words you can believe:" },
    { type: "paragraph", text: "I can be nervous and still be prepared." },
    { type: "paragraph", text: "I have learned difficult things before." },
    { type: "paragraph", text: "I can listen, count, and take the next entrance." },
    { type: "paragraph", text: "One mistake does not erase my work." },
    { type: "paragraph", text: "I belong here with my band." },
    { type: "paragraph", text: "I can ask for help." },
    { type: "paragraph", text: "You do not have to convince yourself that everything will be perfect. Give yourself something useful to hold on to." },
    { type: "heading", text: "Give Yourself One Next Step" },
    { type: "paragraph", text: "Your mind may try to carry the entire performance at once: every entrance, every formation, every judge, every possible mistake." },
    { type: "paragraph", text: "Bring it back to one manageable action." },
    { type: "paragraph", text: "For a musician, that might be:" },
    { type: "paragraph", text: "Hear the opening tempo. Breathe. Begin." },
    { type: "paragraph", text: "For a color guard member:" },
    { type: "paragraph", text: "Feel my feet. Remember the first count. Follow through." },
    { type: "paragraph", text: "For a percussionist:" },
    { type: "paragraph", text: "Find the pulse. Listen across the line." },
    { type: "paragraph", text: "For anyone:" },
    { type: "paragraph", text: "Do the next thing I have practiced." },
    { type: "paragraph", text: "You have spent weeks learning this show in pieces. You can perform it one moment at a time, too." },
    { type: "heading", text: "Someone Else’s Cruelty Does Not Deserve Your Agreement" },
    { type: "paragraph", text: "A hurtful comment can become even more painful when you begin repeating it to yourself." },
    { type: "paragraph", text: "Someone says, “You’re terrible.”" },
    { type: "paragraph", text: "Then your own thoughts start saying, I’m terrible." },
    { type: "paragraph", text: "Pause before you let their words become yours." },
    { type: "paragraph", text: "You can tell yourself:" },
    { type: "paragraph", text: "That comment hurt. It does not define me." },
    { type: "paragraph", text: "I deserve to be treated with respect." },
    { type: "paragraph", text: "I can take useful corrections without accepting insults." },
    { type: "paragraph", text: "A director pointing out a missed count gives you information you can use. Someone humiliating you gives you something very different." },
    { type: "paragraph", text: "If comments are repeated, threatening, discriminatory, or meant to embarrass or exclude you, tell your director, a chaperone, or another trusted adult. You can say, “This keeps happening, and I need help getting it to stop.”" },
    { type: "paragraph", text: "If you feel unsafe, get an adult’s attention immediately." },
    { type: "paragraph", text: "Turning inward can help you collect your thoughts. You also deserve support from the people responsible for your care." },
    { type: "heading", text: "Let Music Help You Find the Words" },
    { type: "paragraph", text: "Some days, you know exactly what you need to hear." },
    { type: "paragraph", text: "Other days, the words will not come." },
    { type: "paragraph", text: "That is when a song can give you a place to begin." },
    { type: "paragraph", text: "Listen for a line that feels useful today. You do not have to feel everything the singer feels or believe every word immediately. Let one phrase stay with you." },
    { type: "paragraph", text: "Perhaps it is:" },
    { type: "paragraph", text: "“I’ve been learning all along.”" },
    { type: "paragraph", text: "Remember something you can do now that you could not do at the beginning of the season." },
    { type: "paragraph", text: "Perhaps it is:" },
    { type: "paragraph", text: "“My voice matters, even when I feel small.”" },
    { type: "paragraph", text: "Remember that your contribution belongs in this performance." },
    { type: "paragraph", text: "Or perhaps all you need is the invitation to pause and take a breath." },
    { type: "heading", text: "Carry Your Own Voice Onto the Field" },
    { type: "paragraph", text: "What you say to yourself matters because it can shape what you pay attention to next." },
    { type: "paragraph", text: "If your inner voice keeps repeating an insult, it can be harder to notice the count, the conductor, or the friend offering encouragement. A steadier voice can help bring your attention back to the work in front of you." },
    { type: "paragraph", text: "It will not erase every nervous feeling. You can still give yourself kindness, direction, and room to recover." },
    { type: "paragraph", text: "Before you step off the bus, choose one sentence to take with you:" },
    { type: "paragraph", text: "I am ready to do my part." },
    { type: "paragraph", text: "Or:" },
    { type: "paragraph", text: "I can be brave while I am nervous." },
    { type: "paragraph", text: "Or simply:" },
    { type: "paragraph", text: "Breathe. Listen. Begin." },
    { type: "paragraph", text: "The bus will get loud again. Your friends will need you. Soon, it will be time to gather your things and move." },
    { type: "paragraph", text: "For this minute, let your own voice be one that helps." },
  ],
};
