"use client";

import Link from "next/link";
import { useEffect, useMemo, useRef, useState } from "react";
import type { ReactNode } from "react";

type Tune = { title: string; file: string; choices: string[] };

const tunes: Tune[] = [
  { title: "2001 Fanfare", file: "2001 Fanfare.mp3", choices: ["2001 Fanfare", "Olympic Fanfare", "Battle Hymn", "William Tell"] },
  { title: "America the Beautiful", file: "America the Beautiful.mp3", choices: ["America the Beautiful", "Stars and Stripes Forever", "The Horse", "Birdland"] },
  { title: "Battle Hymn", file: "Battle Hymn.mp3", choices: ["Battle Hymn", "Strike Up the Band", "MacArthur Park", "Champions"] },
  { title: "Birdland", file: "Birdland.mp3", choices: ["Birdland", "Sing, Sing, Sing", "Shout It Out!", "Ghostbusters"] },
  { title: "Eye of the Tiger", file: "Eye of the Tiger.mp3", choices: ["Eye of the Tiger", "Survivor", "Gonna Fly Now", "Seven Nation Army"] },
  { title: "Stars and Stripes Forever", file: "Stars and Stripes Forever - Michigan Marching Band 2012 @ Crisler Concert.mp3", choices: ["Stars and Stripes Forever", "America the Beautiful", "William Tell", "2001 Fanfare"] },
];

const trivia = [
  ["Which section usually does not march?", ["Drum line", "The pit", "Sousaphones", "Baritone saxophones"], "The pit"],
  ["What is the role of a drum major?", ["Conduct the band", "Play the largest drum", "Lead the color guard", "Judge the show"], "Conduct the band"],
  ["What does G.E. mean in marching-band judging?", ["Greatest Energy", "General Effect", "Good Execution", "Group Expression"], "General Effect"],
  ["What instrument typically maintains the marching tempo?", ["Trumpet", "Clarinet", "Snare drum", "Trombone"], "Snare drum"],
  ["How many steps are commonly taken for five yards?", ["5", "8", "10", "12"], "8"],
] as const;

const collegeSongs = [
  ["University of Oklahoma", "Boomer Sooner", "Crimson and Cream", "5ErtzJSUiQY"],
  ["University of Wisconsin", "On, Wisconsin!", "Cardinal and White", "DPwDoTbRDag"],
  ["University of Tennessee", "Rocky Top", "Orange and White", "vDDy8_H2XnA"],
  ["University of Michigan", "The Victors", "Maize and Blue", "H80UZVzIbzg"],
] as const;

const crosswordWords = [
  ["Beat played by percussion during a parade", "CADENCE"],
  ["Student conductor who directs the band", "DRUMMAJOR"],
  ["Marching in place", "MARKTIME"],
  ["Speed of the music", "TEMPO"],
  ["A band that moves and plays", "MARCHINGBAND"],
] as const;

const shell = (title: string, children: ReactNode) => (
  <main className="min-h-screen bg-[var(--cream)] px-6 pb-20 pt-32 text-[var(--navy)] sm:px-10 lg:px-16">
    <div className="mx-auto max-w-5xl">
      <Link href="/play" className="text-sm font-bold text-[var(--purple)]">← Back to games</Link>
      <p className="mt-10 text-xs font-bold uppercase tracking-[0.28em] text-[var(--purple)]">On the Bus to Contest</p>
      <h1 className="mt-4 text-5xl leading-[.92] sm:text-7xl">{title}</h1>
      <section className="mt-10 rounded-[28px] border border-[var(--navy)]/10 bg-white p-6 shadow-[0_18px_55px_rgba(7,26,47,.12)] sm:p-10">{children}</section>
    </div>
  </main>
);

function StartCard({ title, description, onStart }: { title: string; description: string; onStart: () => void }) {
  return <div className="mx-auto max-w-2xl text-center"><p className="text-lg leading-8 text-[var(--slate)]">{description}</p><button type="button" onClick={onStart} className="mt-8 rounded-full bg-[var(--gold)] px-7 py-4 text-sm font-bold text-[var(--navy)] transition hover:bg-[var(--champagne)]">Start {title}</button></div>;
}

function NameThatTune() {
  const [started, setStarted] = useState(false); const [round, setRound] = useState(0); const [score, setScore] = useState(0); const [answered, setAnswered] = useState<string | null>(null); const audioRef = useRef<HTMLAudioElement>(null);
  const current = tunes[round % tunes.length];
  const choices = useMemo(() => [...current.choices].sort(() => Math.random() - .5), [current]);
  const answer = (choice: string) => { if (answered) return; setAnswered(choice); if (choice === current.title) setScore((value) => value + 1); };
  if (!started) return shell("Name That Marching Band Tune", <StartCard title="Game" description="Listen to a short marching-band clip, then choose the tune. Six rounds, one point each." onStart={() => setStarted(true)} />);
  if (round >= 6) return shell("Name That Marching Band Tune", <div className="text-center"><p className="text-sm font-bold uppercase tracking-[.25em] text-[var(--purple)]">Final score</p><h2 className="mt-3 text-6xl">{score} / 6</h2><button type="button" onClick={() => { setRound(0); setScore(0); setAnswered(null); }} className="mt-8 rounded-full bg-[var(--gold)] px-7 py-4 text-sm font-bold">Play again</button></div>);
  return shell("Name That Marching Band Tune", <div><div className="flex items-center justify-between text-sm font-bold"><span>Round {round + 1} / 6</span><span>Score {score}</span></div><audio ref={audioRef} src={`/content/audio/name-that-tune/${encodeURIComponent(current.file)}`} controls className="mt-8 w-full" onPlay={() => undefined} /><p className="mt-6 text-center text-sm text-[var(--slate)]">Listen first, then make your best call.</p><div className="mt-7 grid gap-3 sm:grid-cols-2">{choices.map((choice) => <button key={choice} type="button" disabled={!!answered} onClick={() => answer(choice)} className={`rounded-2xl border px-5 py-4 text-left font-semibold transition ${answered ? choice === current.title ? "border-green-600 bg-green-50" : choice === answered ? "border-red-500 bg-red-50" : "opacity-50" : "border-[var(--navy)]/15 hover:border-[var(--gold)]"}`}>{choice}</button>)}</div>{answered && <div className="mt-7 flex items-center justify-between"><p className="font-bold">{answered === current.title ? "Correct!" : `The answer was ${current.title}.`}</p><button type="button" onClick={() => { setRound((value) => value + 1); setAnswered(null); }} className="rounded-full bg-[var(--gold)] px-6 py-3 text-sm font-bold">Next round →</button></div>}</div>);
}

function CollegeFightSongs() {
  const [round, setRound] = useState(0); const [started, setStarted] = useState(false); const [score, setScore] = useState(0); const [answer, setAnswer] = useState<string | null>(null); const song = collegeSongs[round % collegeSongs.length]; const options = useMemo(() => [...collegeSongs.map((item) => item[0])].sort(() => Math.random() - .5), [song]);
  if (!started) return shell("Name That College", <StartCard title="Game" description="Play a fight-song clip, use the clues if you need them, and identify the college." onStart={() => setStarted(true)} />);
  if (round >= 6) return shell("Name That College", <div className="text-center"><p className="text-sm font-bold uppercase tracking-[.25em] text-[var(--purple)]">Final score</p><h2 className="mt-3 text-6xl">{score} / 6</h2><button type="button" onClick={() => { setRound(0); setScore(0); setAnswer(null); }} className="mt-8 rounded-full bg-[var(--gold)] px-7 py-4 text-sm font-bold">Play again</button></div>);
  const choose = (value: string) => { if (answer) return; setAnswer(value); if (value === song[0]) setScore((value) => value + 1); };
  return shell("Name That College", <div><div className="flex items-center justify-between text-sm font-bold"><span>Round {round + 1} / 6</span><span>Score {score}</span></div><div className="mt-7 overflow-hidden rounded-2xl bg-[var(--navy)]"><iframe title="Fight song preview" className="h-24 w-full" src={`https://www.youtube.com/embed/${song[3]}?rel=0`} allow="autoplay; encrypted-media" /></div><div className="mt-6 rounded-2xl bg-[var(--cream)] p-5 text-sm leading-7"><p><strong>Clue 1:</strong> Team colors are {song[2]}.</p>{answer && <p><strong>Song:</strong> {song[1]}</p>}</div><div className="mt-6 grid gap-3 sm:grid-cols-2">{options.map((option) => <button key={option} type="button" disabled={!!answer} onClick={() => choose(option)} className={`rounded-2xl border px-5 py-4 text-left font-semibold ${answer ? option === song[0] ? "border-green-600 bg-green-50" : option === answer ? "border-red-500 bg-red-50" : "opacity-50" : "border-[var(--navy)]/15 hover:border-[var(--gold)]"}`}>{option}</button>)}</div>{answer && <div className="mt-7 flex items-center justify-between"><p className="font-bold">{answer === song[0] ? "Correct!" : `It was ${song[0]}.`}</p><button type="button" onClick={() => { setRound((value) => value + 1); setAnswer(null); }} className="rounded-full bg-[var(--gold)] px-6 py-3 text-sm font-bold">Next round →</button></div>}</div>);
}

function Trivia() { const [index, setIndex] = useState(0); const [score, setScore] = useState(0); const [done, setDone] = useState(false); if (done) return shell("Marching Band Trivia", <div className="text-center"><h2 className="text-6xl">{score} / {trivia.length}</h2><button type="button" onClick={() => { setIndex(0); setScore(0); setDone(false); }} className="mt-8 rounded-full bg-[var(--gold)] px-7 py-4 text-sm font-bold">Play again</button></div>); const item = trivia[index]; return shell("Marching Band Trivia", <div><p className="text-sm font-bold text-[var(--purple)]">Question {index + 1} / {trivia.length}</p><h2 className="mt-5 text-3xl leading-tight">{item[0]}</h2><div className="mt-7 grid gap-3">{item[1].map((option) => <button key={option} type="button" onClick={() => { if (option === item[2]) setScore((value) => value + 1); if (index === trivia.length - 1) setDone(true); else setIndex((value) => value + 1); }} className="rounded-2xl border border-[var(--navy)]/15 px-5 py-4 text-left font-semibold transition hover:border-[var(--gold)]">{option}</button>)}</div><p className="mt-7 text-sm text-[var(--slate)]">Score: {score}</p></div>); }

function TicTapTone() { const [mode, setMode] = useState<"single" | "two">("single"); const [board, setBoard] = useState<("Trombone" | "Drummer" | null)[]>(Array(9).fill(null)); const [player, setPlayer] = useState<"Trombone" | "Drummer">("Trombone"); const winner = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].find(([a,b,c]) => board[a] && board[a] === board[b] && board[a] === board[c]); const move = (index: number) => { if (board[index] || winner) return; const next = [...board]; next[index] = player; setBoard(next); setPlayer(player === "Trombone" ? "Drummer" : "Trombone"); }; return shell("Tic Tap Tone", <div className="mx-auto max-w-md text-center"><div className="flex justify-center gap-3"><button type="button" onClick={() => { setMode("single"); setBoard(Array(9).fill(null)); setPlayer("Trombone"); }} className={`rounded-full px-4 py-2 text-sm font-bold ${mode === "single" ? "bg-[var(--gold)]" : "bg-[var(--cream)]"}`}>Single player</button><button type="button" onClick={() => { setMode("two"); setBoard(Array(9).fill(null)); setPlayer("Trombone"); }} className={`rounded-full px-4 py-2 text-sm font-bold ${mode === "two" ? "bg-[var(--gold)]" : "bg-[var(--cream)]"}`}>Two player</button></div><p className="mt-7 font-bold">{winner ? `${board[winner[0]]} wins!` : `${player}'s turn`}</p><div className="mt-5 grid grid-cols-3 gap-2">{board.map((value, index) => <button key={index} type="button" onClick={() => move(index)} className="aspect-square rounded-2xl bg-[var(--navy)] text-2xl font-bold text-[var(--gold)]">{value === "Trombone" ? "🎺" : value === "Drummer" ? "🥁" : ""}</button>)}</div><button type="button" onClick={() => { setBoard(Array(9).fill(null)); setPlayer("Trombone"); }} className="mt-7 rounded-full border border-[var(--navy)]/20 px-6 py-3 text-sm font-bold">Reset board</button></div>); }

function Crossword() { const [answers, setAnswers] = useState<string[]>(Array(crosswordWords.length).fill("")); const [checked, setChecked] = useState(false); const solved = answers.every((answer, index) => answer.toUpperCase() === crosswordWords[index][1]); return shell("Marching Band Terms Crossword", <div><p className="text-[var(--slate)]">Fill the answers from the clues, then check your work.</p><div className="mt-7 grid gap-4">{crosswordWords.map(([clue, answer], index) => <label key={answer} className="grid gap-2 font-semibold"><span><b>{index + 1}.</b> {clue}</span><input value={answers[index]} onChange={(event) => { const next = [...answers]; next[index] = event.target.value; setAnswers(next); setChecked(false); }} className="rounded-xl border border-[var(--navy)]/15 px-4 py-3 uppercase outline-none focus:border-[var(--gold)]" /></label>)}</div><button type="button" onClick={() => setChecked(true)} className="mt-7 rounded-full bg-[var(--gold)] px-7 py-3 text-sm font-bold">Check answers</button>{checked && <p className="mt-5 font-bold">{solved ? "Puzzle solved — nice work!" : "A few answers still need another look."}</p>}</div>); }

function HalftimeHustle() { const [playing, setPlaying] = useState(false); const [lane, setLane] = useState(1); const [score, setScore] = useState(0); useEffect(() => { if (!playing) return; const timer = window.setInterval(() => setScore((value) => value + 1), 500); const onKey = (event: KeyboardEvent) => { if (event.key === "ArrowLeft") setLane((value) => Math.max(0, value - 1)); if (event.key === "ArrowRight") setLane((value) => Math.min(2, value + 1)); }; window.addEventListener("keydown", onKey); return () => { window.clearInterval(timer); window.removeEventListener("keydown", onKey); }; }, [playing]); return shell("The Dodging Judge", <div className="text-center"><p className="text-[var(--slate)]">Use the left and right arrow keys to change lanes and keep marching.</p><div className="relative mx-auto mt-8 h-72 max-w-md overflow-hidden rounded-3xl bg-[linear-gradient(90deg,#38674f_0_33%,#4e805d_33%_66%,#38674f_66%)]"><div className="absolute inset-y-0 left-1/3 border-l-2 border-dashed border-white/30" /><div className="absolute inset-y-0 left-2/3 border-l-2 border-dashed border-white/30" /><div className="absolute bottom-8 text-3xl transition-all" style={{ left: `${lane * 33 + 13}%` }}>🏃</div><div className="absolute right-4 top-4 rounded-full bg-white/90 px-3 py-1 text-sm font-bold">{score}</div></div><button type="button" onClick={() => { setPlaying(true); setScore(0); }} className="mt-7 rounded-full bg-[var(--gold)] px-7 py-3 text-sm font-bold">{playing ? "Keep marching" : "Start run"}</button></div>); }

function ScavengerHunt() { const items = ["tree", "cake", "glasses", "pickles", "lawnmower", "panda", "note", "chandlier"]; const [found, setFound] = useState<string[]>([]); return shell("Bus Ride Scavenger Hunt", <div><p className="text-[var(--slate)]">Find all eight hidden items in the picture.</p><div className="relative mt-7 overflow-hidden rounded-2xl"><img src="/content/images/scavenger.png" alt="Illustrated scavenger hunt scene" className="w-full" />{items.map((item, index) => <button key={item} type="button" aria-label={`Find item ${index + 1}`} onClick={() => setFound((value) => value.includes(item) ? value : [...value, item])} className={`absolute h-12 w-12 rounded-full border-2 ${found.includes(item) ? "border-green-400 bg-green-400/70" : "border-transparent bg-transparent hover:border-[var(--gold)]"}`} style={{ left: `${12 + (index * 11) % 75}%`, top: `${18 + (index * 17) % 62}%` }}>{found.includes(item) ? "✓" : ""}</button>)}</div><p className="mt-5 font-bold">{found.length} / 8 found</p>{found.length === 8 && <button type="button" onClick={() => setFound([])} className="mt-5 rounded-full bg-[var(--gold)] px-6 py-3 text-sm font-bold">Play again</button>}</div>); }

function Coloring() { const [color, setColor] = useState("#e2b24f"); const [fills, setFills] = useState<string[]>([]); const swatches = ["#e2b24f", "#80558d", "#2d6a68", "#d65b45", "#f5efe2", "#14203d"]; return shell("Coloring on the Road", <div className="text-center"><p className="text-[var(--slate)]">Choose a color, then tap the flag panels to bring the design to life.</p><div className="mx-auto mt-8 grid max-w-2xl grid-cols-3 gap-3 sm:grid-cols-4">{[1,2,3,4,5,6,7,8].map((id) => <button key={id} type="button" onClick={() => setFills((value) => value.includes(String(id)) ? value.filter((item) => item !== String(id)) : [...value, String(id)])} className="aspect-square rounded-xl border-4 border-white shadow transition hover:scale-105" style={{ backgroundColor: fills.includes(String(id)) ? color : "#f4eee0" }}><span className="text-2xl">{fills.includes(String(id)) ? "★" : ""}</span></button>)}</div><div className="mt-7 flex flex-wrap justify-center gap-3">{swatches.map((swatch) => <button key={swatch} type="button" aria-label={`Choose ${swatch}`} onClick={() => setColor(swatch)} className={`h-9 w-9 rounded-full border-4 ${color === swatch ? "border-[var(--navy)]" : "border-white"}`} style={{ backgroundColor: swatch }} />)}</div><button type="button" onClick={() => setFills([])} className="mt-7 rounded-full border border-[var(--navy)]/20 px-6 py-3 text-sm font-bold">Clear page</button></div>); }

export function InteractiveGame({ slug }: { slug: string }) { switch (slug) { case "name-that-tune": return <NameThatTune />; case "college-fight-songs": return <CollegeFightSongs />; case "marching-band-crossword": return <Crossword />; case "trivia": return <Trivia />; case "tic-tac-toe": return <TicTapTone />; case "halftime-hustle": return <HalftimeHustle />; default: return shell("Game not found", <p>That game is not available yet.</p>); } }
export function InteractiveActivity({ slug }: { slug: string }) { switch (slug) { case "scavenger-hunt": return <ScavengerHunt />; case "coloring": return <Coloring />; default: return shell("Activity not found", <p>That activity is not available yet.</p>); } }
