"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import { SiteNav } from "@/components/navigation/SiteNav";
import { StoriesBehindContent } from "@/components/books/stories-behind/StoriesBehindContent";

export default function StoriesBehindMarchingBandPage() {
  const [showRail, setShowRail] = useState(false);
  return <main className="min-h-screen bg-[#f7f4ee] pt-[76px] text-[#0a1023]"><SiteNav solid /><div className="relative min-h-[390px] overflow-hidden border-b border-[#071126]/10 bg-[#f7f4ee] px-7 pb-12 pt-14 sm:px-12 lg:px-16 lg:pt-10"><Image src="/images/books/hero-bg.png" alt="Marching band students on the road" fill sizes="100vw" className="object-cover object-center opacity-90" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(250,248,243,.98)_0%,rgba(250,248,243,.92)_43%,rgba(250,248,243,.28)_70%,rgba(7,17,38,.1)_100%)]" /><div className="relative max-w-4xl"><Link href="/books" className="inline-flex text-sm font-bold text-[var(--purple)]">← Back to books</Link><p className="mt-12 text-xs font-bold uppercase tracking-[0.35em] text-[#2d3550]">History and tradition</p><h1 className="mt-5 max-w-4xl text-5xl leading-[.88] sm:text-6xl lg:text-[5.2rem]">The Stories Behind<br />Marching Band</h1><p className="mt-5 max-w-2xl font-[family-name:var(--font-display)] text-2xl leading-tight sm:text-3xl">Every tradition has a story. Every rehearsal continues it.</p><p className="mt-5 max-w-xl text-base leading-7 sm:text-lg">By Dr. Randall Bayne · 13 chapters</p></div></div><div className="grid lg:grid-cols-[300px_minmax(0,1fr)]"><aside className={`${showRail ? "block" : "hidden"} border-r border-white/10 bg-[#091328] p-6 text-white lg:block`}><Image src="/content/images/books/stories-behind-marchingbandv3.png" alt="The Stories Behind Marching Band book cover" width={240} height={360} className="mx-auto rounded-xl object-contain" /><p className="mt-6 text-xs font-bold uppercase tracking-[0.25em] text-[var(--gold)]">A longer read for the ride</p><p className="mt-3 text-sm leading-6 text-white/70">A journey through more than 2,000 years of music, discipline, tradition, and the story behind American marching band.</p></aside><section className="min-w-0 bg-[#f7f4ee]"><button type="button" onClick={() => setShowRail((value) => !value)} className="m-5 rounded-full border border-[var(--navy)]/15 bg-white px-4 py-2 text-sm font-bold lg:hidden">{showRail ? "Hide book details" : "Show book details"}</button><StoriesBehindContent /></section></div></main>;
}
