"use client";

import Image from "next/image";
import Link from "next/link";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { MakingFriendsContent, makingFriendsChapters } from "@/components/books/making-friends/MakingFriendsContent";

function BookMarkIcon() { return <svg aria-hidden="true" className="h-6 w-6" viewBox="0 0 24 24" fill="none"><path d="M6 4.75A2.75 2.75 0 0 1 8.75 2h6.5A2.75 2.75 0 0 1 18 4.75V21l-6-3.6L6 21V4.75Z" stroke="currentColor" strokeWidth="1.7" strokeLinejoin="round" /></svg>; }
function OpenBookIcon() { return <svg aria-hidden="true" className="h-7 w-7" viewBox="0 0 32 32" fill="none"><path d="M4.5 7.5c4.7-.6 8.3.5 11.5 3.2v16.8c-3.2-2.7-6.8-3.8-11.5-3.2V7.5Zm23 0c-4.7-.6-8.3.5-11.5 3.2v16.8c-3.2-2.7-6.8-3.8-11.5-3.2V7.5Z" fill="currentColor" stroke="currentColor" strokeWidth="1.2" strokeLinejoin="round" /><path d="M16 10.7v16.8" stroke="#071126" strokeWidth="1.2" /></svg>; }

export default function MakingFriendsPage() {
  const [currentPage, setCurrentPage] = useState(0); const [totalPages, setTotalPages] = useState(43); const [chapterPages, setChapterPages] = useState<Record<string, number>>({ introduction: 0 }); const [bookmarked, setBookmarked] = useState(false); const readerRef = useRef<HTMLElement>(null);
  const onPageCount = useCallback((count: number) => setTotalPages(count), []); const onChapterPages = useCallback((pages: Record<string, number>) => setChapterPages(pages), []);
  const manuscript = useMemo(() => <MakingFriendsContent pageIndex={currentPage} onPageCount={onPageCount} onChapterPages={onChapterPages} />, [currentPage, onPageCount, onChapterPages]);
  const goToPage = useCallback((page: number) => { const next = Math.max(0, Math.min(totalPages - 1, page)); setCurrentPage(next); readerRef.current?.scrollTo({ top: 0, behavior: "smooth" }); }, [totalPages]);
  useEffect(() => { readerRef.current?.scrollTo({ top: 0, behavior: "auto" }); }, [currentPage]);

  return <main className="min-h-screen bg-[#f7f4ee] text-[#0a1023]"><header className="sticky top-0 z-30 flex min-h-[72px] items-center gap-7 border-b border-white/10 bg-[#071126] px-5 py-3 text-white sm:px-8 lg:gap-12 lg:px-8"><Link href="/" className="flex shrink-0 items-center gap-3 text-white"><span className="flex h-9 w-9 items-center justify-center text-[var(--gold)]"><OpenBookIcon /></span><span className="font-[family-name:var(--font-display)] text-xl leading-none sm:text-2xl">On the Bus to Contest</span></Link><nav aria-label="Book navigation" className="hidden items-center gap-8 text-sm lg:flex">{[["Home", "/"], ["Games", "/play"], ["Coloring", "/activities/coloring"], ["Books", "/books"], ["Articles", "/read"]].map(([label, href]) => <Link key={label} href={href} className={`relative py-5 ${label === "Books" ? "text-white after:absolute after:bottom-1 after:left-0 after:right-0 after:h-0.5 after:bg-[var(--gold)]" : "text-white/90"}`}>{label}</Link>)}</nav><button type="button" aria-label="Bookmark book" aria-pressed={bookmarked} onClick={() => setBookmarked((value) => !value)} className={`ml-auto transition hover:text-[var(--gold)] ${bookmarked ? "text-[var(--gold)]" : "text-white/90"}`}><BookMarkIcon /></button></header>
    <div className="grid md:h-[calc(100vh-72px)] md:overflow-hidden md:grid-cols-[230px_minmax(0,1fr)] lg:grid-cols-[310px_minmax(0,1fr)]"><aside className="relative z-20 max-h-[calc(100vh-72px)] overflow-y-auto border-r border-white/10 bg-[#091328] px-4 py-5 text-white md:h-full md:min-h-0 md:py-6 lg:px-7 lg:py-7"><div className="mx-auto max-w-[255px]"><div className="relative aspect-[.82] overflow-hidden rounded-xl border border-white/35 shadow-[0_18px_35px_rgba(0,0,0,.28)] lg:aspect-[.66]"><Image src="/images/books/books-cover/making_friends.png" alt="Making Friends on the Band Bus book cover" fill sizes="255px" className="object-cover" /></div><nav aria-label="Chapters" className="mt-5 space-y-1.5 lg:mt-7 lg:space-y-2">{makingFriendsChapters.map((chapter, index) => <button type="button" key={chapter.id} onClick={() => goToPage(chapterPages[chapter.id] ?? index)} aria-current={currentPage === (chapterPages[chapter.id] ?? -1) ? "page" : undefined} className={`flex w-full items-center gap-3 rounded-xl px-3 py-2.5 text-left text-sm transition hover:bg-white/10 lg:gap-4 lg:py-3 ${currentPage === (chapterPages[chapter.id] ?? -1) ? "bg-[#f5c96a] font-medium text-[#1a1b22]" : "text-white/90"}`}><span className="flex h-8 w-8 shrink-0 items-center justify-center rounded-full bg-white/10 text-xs font-medium lg:h-9 lg:w-9">{index === 0 ? "" : index}</span><span>{index === 0 ? "Introduction" : chapter.title}</span></button>)}</nav></div></aside>
      <section ref={readerRef} className="relative min-w-0 overflow-hidden bg-[#f7f4ee] md:h-full md:overflow-y-auto"><div className="relative min-h-[360px] overflow-hidden border-b border-[#071126]/10 bg-[#f7f4ee] px-7 pb-12 pt-14 sm:min-h-[390px] sm:px-12 lg:min-h-[430px] lg:px-16 lg:pt-10"><Image src="/images/books/book-view/firstnote/hero-bg.png" alt="Sunset view from a bus window" fill sizes="(max-width: 1024px) 100vw, 80vw" className="object-cover object-center opacity-90" /><div className="absolute inset-0 bg-[linear-gradient(90deg,rgba(250,248,243,.98)_0%,rgba(250,248,243,.92)_43%,rgba(250,248,243,.3)_67%,rgba(7,17,38,.1)_100%)]" /><div className="relative max-w-3xl"><p className="text-xs font-bold uppercase tracking-[0.35em] text-[#2d3550]">A practical guide for the ride</p><h1 className="mt-5 text-5xl leading-[.88] sm:text-6xl lg:text-[5.2rem]">Making Friends<br />on the Band Bus</h1><div className="mt-5 h-0.5 w-14 bg-[var(--gold)]" /><p className="mt-5 max-w-xl text-base leading-7 sm:text-lg">How to meet people, make someone laugh, be a good friend, and make the ride better for everyone.</p></div></div><div className="relative z-10 mx-5 -mt-1 rounded-[18px] bg-[#fffdfa] px-7 py-7 shadow-[0_18px_45px_rgba(20,27,44,.1)] sm:mx-10 sm:px-12 sm:py-9 lg:mx-12 lg:px-12 lg:py-10 xl:mx-14"><div className="flex items-center justify-between gap-4"><div><p className="text-xs font-bold uppercase tracking-[0.3em] text-[#27304a]">Making Friends on the Band Bus</p><div className="mt-3 h-0.5 w-14 bg-[var(--gold)]" /></div><div className="flex items-center gap-3 text-[#26304b]"><span className="hidden text-xs font-semibold uppercase tracking-[0.12em] text-[#6c7180] sm:inline">Chapter {String(currentPage + 1).padStart(2, "0")} / {String(totalPages).padStart(2, "0")}</span><button type="button" aria-label="Previous chapter" disabled={currentPage === 0} onClick={() => goToPage(currentPage - 1)} className="flex h-10 w-10 items-center justify-center rounded-full border border-[#14203d]/10 text-2xl transition hover:border-[var(--gold)] disabled:cursor-not-allowed disabled:opacity-35">‹</button><button type="button" aria-label="Next chapter" disabled={currentPage >= totalPages - 1} onClick={() => goToPage(currentPage + 1)} className="flex h-10 w-10 items-center justify-center rounded-full border border-[#14203d]/10 text-2xl transition hover:border-[var(--gold)] disabled:cursor-not-allowed disabled:opacity-35">›</button></div></div><div className="mt-8">{manuscript}</div></div></section></div></main>;
}
