"use client";

import { useEffect, useMemo, useState, type ReactNode } from "react";
import { beforeTheFirstNoteSections } from "@/content/books/beforeTheFirstNote";

export const texts = beforeTheFirstNoteSections.map((section) => section.text);
const poemTitles = new Set(["The Bus Is Moving", "You Do Not Have to Be Fearless", "Look Beside You", "The Person Who Looks Calm", "For the Freshman", "For the Senior", "The Quiet Student", "Thank the Bus Driver", "The Uniform", "Before the First Note", "One Count at a Time", "When the Warm-Up Is Bad", "The Director at the Front", "To the One Who Is Scared", "Play for Someone", "When They Say Your Name", "The Gate", "The Hands That Got You Here", "The Field Is Waiting", "If You Miss", "Your Best Is Not Perfect", "Another Band", "The Person in Row Forty", "Stadium Lights", "The Middle of the Show", "Listen Across the Band", "The Final Chord", "After the Last Note", "The Scoreboard", "If They Call Your Name", "If They Don't Call Your Name", "Whatever the Judge Says", "On the Ride Home", "Tomorrow's Rehearsal", "Leave Something on the Field", "We Were Here"]);
const partNames: Record<string, { id: string; subtitle: string }> = { "PART ONE": { id: "part-one", subtitle: "The Ride There" }, "PART TWO": { id: "part-two", subtitle: "Before You Perform" }, "PART THREE": { id: "part-three", subtitle: "On the Field" }, "PART FOUR": { id: "part-four", subtitle: "The Ride Home" } };
const endMarkers = new Set(["Take This With You", "FROM A BAND BUS", "THEY WERE IN BAND TOO", "PART ONE", "PART TWO", "PART THREE", "PART FOUR", "A WORD TO THE DIRECTOR", "A WORD TO THE PEOPLE IN THE STANDS", "PEOPLE BEHIND THE WORDS", "About the Band Member Reflections", "About the Quotations"]);
const journalEnd = new Set(["A WORD TO THE DIRECTOR", "A WORD TO THE PEOPLE IN THE STANDS", "PEOPLE BEHIND THE WORDS"]);

export function slugify(value: string) { return value.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, ""); }
function Paragraph({ children }: { children: ReactNode }) { return <p className="mb-5 whitespace-pre-line text-[1.05rem] leading-8 text-[#35405b]">{children}</p>; }
function PartHeader({ label, subtitle }: { label: string; subtitle: string }) { return <section id={partNames[label].id} className="scroll-mt-8 border-t border-[#14203d]/10 pt-8"><p className="text-xs font-bold uppercase tracking-[0.3em] text-[#80558d]">{label}</p><h2 className="mt-3 font-[family-name:var(--font-display)] text-5xl leading-[.9] text-[#0a1023]">{subtitle}</h2></section>; }
function PoemPage({ title, lines, fontScale }: { title: string; lines: string[]; fontScale: number }) { return <article id={slugify(title)} className="my-3 scroll-mt-8" style={{ fontSize: `${fontScale}em` }}><p className="text-xs font-bold uppercase tracking-[0.3em] text-[#80558d]">Poem</p><h3 className="mt-3 font-[family-name:var(--font-display)] text-4xl leading-[.95] text-[#0a1023] sm:text-5xl">{title}</h3><div className="mt-6 max-w-2xl">{lines.map((line, index) => <Paragraph key={`${title}-${index}`}>{line}</Paragraph>)}</div></article>; }
function ProfilePage({ title, lines, fontScale }: { title: string; lines: string[]; fontScale: number }) { return <section className="my-3 overflow-hidden rounded-[22px] border border-[#d7cbe0] bg-[#faf6fb]" style={{ fontSize: `${fontScale}em` }}><div className="border-b border-[#d7cbe0] bg-[#80558d] px-7 py-5 text-white sm:px-9"><p className="text-xs font-bold uppercase tracking-[0.3em] text-[#f5c96a]">They were in band too</p><h3 className="mt-2 font-[family-name:var(--font-display)] text-3xl leading-tight">{title}</h3></div><div className="p-7 sm:p-9">{lines.map((line, index) => <Paragraph key={`${title}-${index}`}>{line}</Paragraph>)}</div></section>; }
function JournalPage({ id, title, prompts, fontScale }: { id: string; title: string; prompts: string[]; fontScale: number }) { const storageKey = `before-the-first-note-${slugify(title)}`; const [answers, setAnswers] = useState<Record<string, string>>({}); useEffect(() => { try { setAnswers(JSON.parse(localStorage.getItem(storageKey) || "{}")); } catch { setAnswers({}); } }, [storageKey]); function update(prompt: string, value: string) { const next = { ...answers, [prompt]: value }; setAnswers(next); localStorage.setItem(storageKey, JSON.stringify(next)); } return <section id={id} className="rounded-[22px] border border-[#e2b24f]/60 bg-[#fffdfa] p-7 shadow-[0_12px_35px_rgba(20,27,44,.08)] sm:p-10" style={{ fontSize: `${fontScale}em` }}><p className="text-xs font-bold uppercase tracking-[0.3em] text-[#80558d]">Reflection page</p><h2 className="mt-3 font-[family-name:var(--font-display)] text-4xl leading-none">{title}</h2><p className="mt-4 max-w-2xl text-base leading-7 text-[#536079]">Take a quiet minute to write what you want to remember. Your answers stay on this device.</p><div className="mt-8 grid gap-5">{prompts.map((prompt) => <label key={prompt} className="grid gap-2 text-base font-semibold text-[#27304a]"><span>{prompt}</span><textarea value={answers[prompt] || ""} onChange={(event) => update(prompt, event.target.value)} rows={2} className="w-full resize-y rounded-xl border border-[#14203d]/15 bg-white px-4 py-3 font-sans text-base font-normal outline-none transition focus:border-[#e2b24f] focus:ring-2 focus:ring-[#e2b24f]/20" /></label>)}</div></section>; }

type BookPage = { blocks: ReactNode[]; chapter?: string };
type BookPages = { pages: BookPage[]; chapterPages: Record<string, number> };

function buildPages(fontScale: number): BookPages {
  const pages: BookPage[] = []; const chapterPages: Record<string, number> = {}; let blocks: ReactNode[] = []; let i = 0; let firstPart = true;
  const flush = () => { if (blocks.length) { pages.push({ blocks }); blocks = []; } };
  const add = (node: ReactNode, chapter?: string, forceNew = false) => { if (forceNew) flush(); if (chapter && chapterPages[chapter] === undefined) chapterPages[chapter] = pages.length; blocks.push(node); };
  while (i < texts.length) {
    const text = texts[i];
    if (partNames[text]) { const part = partNames[text]; add(<PartHeader key={text} label={text} subtitle={part.subtitle} />, part.id, true); i += 1; continue; }
    if (text === "THEY WERE IN BAND TOO") { const title = texts[i + 1] || "Band profile"; const body: string[] = []; let j = i + 2; if (texts[j]?.startsWith("[Black-and-white")) j += 1; while (j < texts.length && !endMarkers.has(texts[j]) && !poemTitles.has(texts[j]) && !partNames[texts[j]]) { body.push(texts[j]); j += 1; } add(<ProfilePage key={`profile-${i}`} title={title} lines={body} fontScale={fontScale} />); i = j; continue; }
    if (text === "FROM A BAND BUS") { add(<aside key={`bus-${i}`} className="rounded-r-[20px] border-l-4 border-[#e2b24f] bg-[#fff4d8] px-7 py-6 sm:px-9" style={{ fontSize: `${fontScale}em` }}><p className="text-xs font-bold uppercase tracking-[0.3em] text-[#80558d]">From a band bus</p><p className="mt-4 font-[family-name:var(--font-display)] text-2xl italic leading-tight text-[#26304b]">“{texts[i + 1]}”</p></aside>); i += 2; continue; }
    if (text === "Take This With You") { add(<aside key={`takeaway-${i}`} className="rounded-[18px] border border-[#e2b24f]/60 bg-[#fffdfa] px-7 py-6 shadow-sm sm:px-9" style={{ fontSize: `${fontScale}em` }}><p className="text-xs font-bold uppercase tracking-[0.3em] text-[#80558d]">Take this with you</p><p className="mt-3 font-[family-name:var(--font-display)] text-2xl leading-tight text-[#0a1023]">{texts[i + 1]}</p></aside>); i += 2; continue; }
    if (text === "Before I Step Off This Bus" || (text === "On the Ride Home" && i > 900)) { const prompts: string[] = []; let j = i + 1; while (j < texts.length && !journalEnd.has(texts[j])) { if (texts[j].endsWith(":")) prompts.push(texts[j]); j += 1; } add(<JournalPage key={`journal-${i}`} id={text === "Before I Step Off This Bus" ? "reflections" : "ride-home-reflection"} title={text} prompts={prompts} fontScale={fontScale} />, text === "Before I Step Off This Bus" ? "reflections" : undefined, true); i = j; continue; }
    if (poemTitles.has(text)) { const lines: string[] = []; let j = i + 1; while (j < texts.length && !poemTitles.has(texts[j]) && !endMarkers.has(texts[j]) && !partNames[texts[j]] && texts[j] !== "Before I Step Off This Bus") { lines.push(texts[j]); j += 1; } add(<PoemPage key={`poem-${i}`} title={text} lines={lines} fontScale={fontScale} />); i = j; continue; }
    if (text === "Dedication" || text === "Preface" || text === "How to Use This Book") { const id = text === "Dedication" ? "introduction" : slugify(text); const next = text === "Dedication" ? 16 : text === "Preface" ? 82 : 99; add(<section key={`front-${i}`} id={id} className={`scroll-mt-8 ${firstPart ? "" : "border-t border-[#14203d]/10 pt-8"}`} style={{ fontSize: `${fontScale}em` }}><p className="text-xs font-bold uppercase tracking-[0.3em] text-[#80558d]">{text}</p><div className="mt-6">{texts.slice(i + 1, next).map((line, index) => <Paragraph key={`${text}-${index}`}>{line}</Paragraph>)}</div></section>, "introduction"); i = next; firstPart = false; continue; }
    if (text === "A WORD TO THE DIRECTOR" || text === "A WORD TO THE PEOPLE IN THE STANDS") { const id = text === "A WORD TO THE DIRECTOR" ? "letters" : "stands"; const body: string[] = []; let j = i + 1; while (j < texts.length && !["A WORD TO THE DIRECTOR", "A WORD TO THE PEOPLE IN THE STANDS", "PEOPLE BEHIND THE WORDS"].includes(texts[j])) { body.push(texts[j]); j += 1; } add(<section key={`letter-${i}`} id={id} className="border-t border-[#14203d]/10 pt-8" style={{ fontSize: `${fontScale}em` }}><p className="text-xs font-bold uppercase tracking-[0.3em] text-[#80558d]">Reflection for the community</p><h2 className="mt-3 font-[family-name:var(--font-display)] text-4xl leading-none text-[#0a1023]">{text.replace("A WORD TO ", "").toLowerCase().replace(/(^| )\w/g, (letter) => letter.toUpperCase())}</h2><div className="mt-7 max-w-3xl">{body.map((line, index) => <Paragraph key={`letter-${i}-${index}`}>{line}</Paragraph>)}</div></section>, "letters", true); i = j; continue; }
    if (text === "PEOPLE BEHIND THE WORDS") { add(<section key="people-behind-words" id="people-behind-words" className="border-t border-[#14203d]/10 pt-8" style={{ fontSize: `${fontScale}em` }}><p className="text-xs font-bold uppercase tracking-[0.3em] text-[#80558d]">Reference profiles</p><h2 className="mt-3 font-[family-name:var(--font-display)] text-4xl leading-none text-[#0a1023]">People Behind the Words</h2><div className="mt-6">{texts.slice(i + 1).map((line, index) => <Paragraph key={`people-${index}`}>{line}</Paragraph>)}</div></section>, "people-behind-words", true); break; }
    add(<Paragraph key={`paragraph-${i}`}>{text}</Paragraph>); i += 1;
  }
  flush(); return { pages, chapterPages };
}

export function ManuscriptContent({ fontScale, pageIndex, onPageCount, onChapterPages }: { fontScale: number; pageIndex: number; onPageCount: (count: number) => void; onChapterPages: (pages: Record<string, number>) => void }) {
  const book = useMemo(() => buildPages(fontScale), [fontScale]); const safeIndex = Math.max(0, Math.min(pageIndex, book.pages.length - 1));
  useEffect(() => { onPageCount(book.pages.length); onChapterPages(book.chapterPages); }, [book, onPageCount, onChapterPages]);
  return <div data-book-page={safeIndex} className="max-w-4xl font-[Georgia,serif] font-normal leading-[1.65]">{book.pages[safeIndex]?.blocks}</div>;
}
