import { Link } from 'react-router-dom';
import { ArrowRight, BookOpen, Gamepad2, Music2, Pencil, Radio } from 'lucide-react';
import PartnersSection from '../PartnersSection';

const offers = [
  { title: 'Articles', description: 'Dive into engaging stories and insights about marching bands, their history, traditions, and achievements.', image: '/images/about/articles-img.png', route: '/articlespage', action: 'Read Articles', Icon: BookOpen },
  { title: 'Games', description: 'Challenge yourself with fun games including music challenges, trivia, crosswords, and interactive puzzles.', image: '/images/home/games/name-that-tune.png', route: '/games', action: 'Play Games', Icon: Gamepad2 },
  { title: 'Radio', description: 'Tune into Between Bands Radio for the soundtrack between performances—featuring high-energy tunes and band tracks.', image: '/images/about/radio-img.png', route: '/radio', action: 'Explore Radio', Icon: Radio },
  { title: 'Activities', description: 'Get creative with coloring pages, scavenger hunts, and interactive challenges made for band people.', image: '/images/coloring-book.jpg', route: '/activitiespage', action: 'Explore Activities', Icon: Pencil },
  { title: 'Books', description: 'Explore stories that celebrate the history, traditions, and people behind marching band.', image: '/images/about/books-img.png', route: '/books', action: 'Explore Books', Icon: BookOpen },
];

export default function About() {
  return <div data-about className="bg-[#F4F0E8] text-[#06182B]">
    <section className="relative isolate flex min-h-[calc(100svh-61px)] items-center overflow-hidden border-b border-[#D6A62E] bg-[#06182B] text-white">
      <div className="absolute inset-0 -z-20 bg-cover bg-[62%_center] sm:bg-[58%_center] lg:bg-[length:115%_auto] lg:bg-right lg:bg-no-repeat" style={{ backgroundImage: "url('/images/about/hero-bg.png')" }} /><div className="absolute inset-0 -z-10" style={{ background: 'linear-gradient(90deg,rgba(3,15,29,.92) 0%,rgba(3,15,29,.62) 47%,rgba(3,15,29,.05) 82%)' }} />
      <div className="mx-auto grid min-h-[calc(100svh-61px)] w-full max-w-[1600px] px-6 py-16 sm:px-12 lg:grid-cols-[96px_1fr] lg:px-0"><div className="hidden border-r border-[#D6A62E]/55 pt-20 lg:block">{[50,40,30,20,10].map(marker => <div key={marker} className="mb-[52px] flex items-center gap-1 text-xs font-black text-[#E8C450]"><span className="h-px w-10 bg-[#D6A62E]" />{marker}</div>)}</div><div className="flex items-center lg:pl-16"><div className="max-w-[650px]"><h1 className="font-display font-black uppercase tracking-[-.025em] text-white" style={{ margin: 0, fontSize: 'clamp(4rem,7vw,7rem)', lineHeight: '.82' }}><span className="block">About</span><span className="block text-[#D6A62E]">Between Bands</span></h1><div className="mt-7 flex items-center gap-4"><span className="h-px w-28 bg-[#D6A62E]" /><Music2 className="text-[#D6A62E]" size={24} /><span className="h-px w-20 bg-[#D6A62E]" /></div><p className="mt-7 max-w-[390px] text-base font-medium leading-relaxed text-white/85 sm:text-lg">The interactive destination for the time between marching-band performances.</p></div></div></div>
    </section>

    <section className="relative flex min-h-[calc(100svh-61px)] items-center overflow-hidden bg-[#F4F0E8] px-6 py-20 sm:px-10 lg:px-16"><div className="pointer-events-none absolute -left-10 bottom-0 font-display text-[280px] leading-none text-[#D6A62E]/[.08]">♪</div><div className="mx-auto grid w-full max-w-[1520px] items-center gap-14 lg:grid-cols-[.9fr_1.1fr] lg:gap-20"><div className="relative z-10"><div className="mb-6 h-1 w-16 bg-[#D6A62E]" /><h2 className="font-display text-6xl font-black uppercase leading-[.86] tracking-[-.02em] lg:text-8xl">Who Are We?</h2><div className="mt-7 flex items-center gap-3"><span className="h-px w-24 bg-[#D6A62E]" /><span className="size-3 rotate-45 border-2 border-[#D6A62E]" /><span className="h-px w-24 bg-[#D6A62E]" /></div><div className="mt-10 max-w-[620px] space-y-7 text-base font-medium leading-[1.8] text-[#243447] sm:text-lg"><p>Welcome to Between Bands, an exhilarating creation brought to you by Accoladi.com. We’ve transformed the spaces “between” those thrilling marching band performances into a world of entertainment and discovery. At the heart of our mission is the recognition that the moments between each band’s awe-inspiring show can often stretch into hours during a marching band competition.</p><p>We’re here to ensure that this downtime becomes a captivating part of the experience. With a treasure trove of articles, Between Bands Radio, and a delightful assortment of games and activities, Between Bands is your go-to source for fun and entertainment during those interludes.</p><p>We’re passionate about celebrating the incredible talent and dedication of marching bands, and we invite you to join us in making the most of the moments between, all while basking in the spirit of musical excellence and community. Welcome to our world. Welcome to Between Bands.</p></div></div><div className="relative min-h-[520px] overflow-hidden rounded-[28px] shadow-[0_28px_65px_rgba(6,24,43,.16)] lg:min-h-[710px]"><img src="/images/about/who-1.png" alt="Marching band drum major and ensemble" className="absolute inset-0 size-full object-cover object-[center_42%]" /><div className="pointer-events-none absolute inset-0 bg-gradient-to-tr from-[#06182B]/20 via-transparent to-white/10" /></div></div></section>

    <section className="flex min-h-[calc(100svh-61px)] items-center border-y border-[#D6A62E]/55 bg-[#06182B] px-6 py-20 text-white sm:px-10 lg:px-16"><div className="mx-auto w-full max-w-[1520px]"><div className="mb-12 flex items-center justify-center gap-7"><span className="h-px flex-1 bg-[#D6A62E]/60" /><div className="text-center"><h2 className="font-display text-5xl font-black uppercase leading-none tracking-[.03em] lg:text-7xl">What We Offer</h2><Music2 className="mx-auto mt-4 text-[#D6A62E]" size={31} /></div><span className="h-px flex-1 bg-[#D6A62E]/60" /></div><div className="grid gap-4 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-5">{offers.map(({ title, description, image, route, action, Icon }) => <article key={title} className="group flex min-h-[520px] flex-col overflow-hidden rounded-2xl border border-[#D6A62E]/70 bg-[#071B30] shadow-[0_22px_50px_rgba(0,0,0,.22)]"><div className="relative h-[240px] shrink-0 overflow-hidden"><img src={image} alt={title} className="size-full object-cover transition duration-500 group-hover:scale-[1.04]" /><div className="absolute inset-0 bg-gradient-to-t from-[#071B30] via-transparent to-black/20" /><div className="absolute left-4 top-4 grid size-[56px] place-items-center rounded-xl border border-[#D6A62E] bg-[#06182B]/90 text-[#D6A62E] shadow-[0_0_0_4px_rgba(6,24,43,.65)]"><Icon size={28} strokeWidth={1.5} /></div></div><div className="flex flex-1 flex-col p-5"><h3 className="font-display text-2xl font-black uppercase leading-none lg:text-3xl">{title}</h3><div className="mt-3 h-[3px] w-10 bg-[#D6A62E]" /><p className="mt-4 text-xs font-medium leading-relaxed text-white/80 sm:text-sm">{description}</p><Link to={route} className="mt-auto inline-flex min-h-10 w-fit items-center gap-2.5 rounded-full border border-[#D6A62E] px-4 py-2 text-xs font-bold uppercase tracking-wide text-[#D6A62E] transition hover:bg-[#D6A62E] hover:text-[#06182B]">{action} <ArrowRight size={15} /></Link></div></article>)}</div></div></section>

    <PartnersSection />
  </div>;
}
