import { Link } from 'react-router-dom';
import { ArrowRight, Gamepad2, Music2, Trophy, Users } from 'lucide-react';
import PartnersSection from '../PartnersSection';

const games = [
  { title: 'Marching Band Terms Crossword', type: 'Word Game', image: '/entertainment/games/marching-band-crossword-1.png', route: '/marching-band-crossword', description: 'Test your marching band vocabulary across easy, medium, and hard crossword puzzles.' },
  { title: 'Name That College', type: 'Music Trivia', image: '/entertainment/games/Name-that-college.png', route: '/college-fight-songs', description: 'Hear a college fight song and guess the school from four choices.' },
  { title: 'The Dodging Judge', type: 'Endless Runner', image: '/images/home/games/the-dodging-judge.png', route: '/halftime-hustle', description: 'Sprint down the field, dodge the judge, and collect music notes!' },
  { title: 'Tic Tap Tone', type: 'vs. a Friend', image: '/entertainment/games/tip-tap-tone.png', route: '/tic-tac-toe', description: 'Play a marching-band spin on tic-tac-toe with trombones and drums.' },
  { title: 'Marching Band Trivia', type: 'Knowledge Game', image: '/entertainment/games/marching-band-trivia.png', route: '/trivia', description: 'Challenge your band knowledge, musical memory, and competition instincts.' },
];

function Scoreboard() {
  return <div className="border border-[#3b6488]/45 bg-[#06182B]/70 p-3 shadow-[inset_0_0_25px_rgba(44,107,158,.18)]">
    <div className="grid grid-cols-3 divide-x divide-[#D6A62E]/30 border border-[#3b6488]/30 font-mono text-[#E8B93D]">
      {[['BB', '24'], ['TIME', '10:00'], ['GUEST', '17']].map(([label, value]) => <div key={label} className="px-3 py-3 text-center sm:px-4"><p className="text-[9px] tracking-widest text-white/55">{label}</p><p className="mt-1 text-xl tracking-[.12em] [text-shadow:0_0_8px_rgba(214,166,46,.4)] sm:text-2xl">{value}</p></div>)}
    </div>
    <p className="mt-1 text-center font-mono text-[9px] tracking-widest text-white/45">QTR&nbsp; <span className="text-[#D6A62E]">2</span></p>
  </div>;
}

function GameCard({ game }) {
  return <article className="group flex h-full flex-col overflow-hidden rounded-[2px] border border-[#06182B]/[.08] bg-white shadow-[0_12px_30px_rgba(6,24,43,.08)] transition duration-300 hover:-translate-y-1 hover:shadow-[0_18px_38px_rgba(6,24,43,.14)]">
    <Link to={game.route} className="relative block aspect-[16/9] overflow-hidden bg-[#DDE3E6]"><img src={game.image} alt="" className="size-full object-cover transition duration-500 group-hover:scale-[1.04]" /><span className="absolute left-3 top-3 bg-[#06182B]/85 px-2.5 py-1 text-[8px] font-black uppercase tracking-[.12em] text-[#F2C550]">{game.type}</span></Link>
    <div className="flex flex-1 flex-col p-[clamp(1rem,1.6vw,1.5rem)]"><h2 className="font-display text-[clamp(1.2rem,1.55vw,1.55rem)] font-black leading-[.95]">{game.title}</h2><p className="mt-3 text-[clamp(.72rem,.75vw,.82rem)] leading-relaxed text-[#526174]">{game.description}</p><Link to={game.route} className="mt-6 inline-flex min-h-10 w-fit items-center gap-5 bg-[#06182B] px-4 text-[9px] font-black uppercase tracking-[.06em] text-white transition hover:bg-[#B6292E]">Play game <ArrowRight size={13} /></Link></div>
  </article>;
}

export default function Games() {
  return <div className="bg-[#F7F5F1] text-[#06182B]">
    <section className="relative isolate overflow-hidden border-b border-[#D6A62E] bg-[#06182B] text-white"><div className="absolute inset-0 -z-30 bg-[url('/images/football-field.jpg')] bg-cover bg-center opacity-25" /><div className="absolute inset-0 -z-20 bg-[linear-gradient(90deg,#06182B_0%,rgba(6,24,43,.93)_42%,rgba(6,24,43,.67)_100%)]" /><div className="absolute inset-0 -z-10 opacity-35 [background-image:radial-gradient(circle_at_center,rgba(214,166,46,.22)_1px,transparent_1px)] [background-size:22px_22px]" /><div className="mx-auto grid min-h-[clamp(430px,36vw,650px)] w-full max-w-[1600px] items-center gap-[clamp(2rem,6vw,8rem)] px-[clamp(1.5rem,5vw,5rem)] py-[clamp(4rem,7vw,7rem)] lg:grid-cols-[.9fr_1.1fr]"><div className="max-w-xl"><p className="text-[10px] font-black uppercase tracking-[.18em] text-[#D6A62E]">Play. Learn. Compete.</p><h1 className="mt-2 font-display text-[clamp(4.8rem,9vw,9rem)] font-black uppercase leading-[.82]">Games</h1><p className="mt-6 max-w-[30rem] text-[clamp(.95rem,1.25vw,1.2rem)] leading-relaxed text-white/80">Fun, challenging, and made for band fans. Test your knowledge, train your brain, and have a blast.</p><a href="#games-list" className="mt-8 inline-flex min-h-12 items-center gap-3 bg-[#F2C550] px-5 text-[10px] font-black uppercase text-[#06182B] transition hover:bg-white"><Gamepad2 size={17} />Challenge yourself</a></div><div className="relative hidden min-h-[clamp(250px,22vw,370px)] lg:block"><div className="absolute right-0 top-0 w-[clamp(260px,24vw,390px)]"><Scoreboard /></div><Music2 className="absolute bottom-10 left-[12%] rotate-[-12deg] text-[#D6A62E]" size={180} strokeWidth={.65} /><div className="absolute bottom-12 right-0 h-px w-[78%] bg-[#D6A62E] shadow-[0_16px_0_#D6A62E,0_32px_0_#D6A62E,0_48px_0_#D6A62E]" /><div className="absolute bottom-0 right-8 flex gap-[clamp(1.5rem,4vw,4rem)] font-display text-[clamp(1.4rem,3vw,2.5rem)] text-white/20">{[50, 40, 30, 20].map(n => <span key={n}>{n}</span>)}</div></div></div></section>

    <main id="games-list" className="scroll-mt-20 px-[clamp(1.25rem,4vw,5rem)] py-[clamp(3.5rem,7vw,7rem)]"><div className="mx-auto w-full max-w-[1600px]"><div className="mb-[clamp(1.5rem,3vw,3rem)] flex flex-wrap items-end justify-between gap-4"><div><p className="mb-2 flex items-center gap-2 text-[10px] font-black uppercase tracking-[.12em] text-[#8b6508]"><Trophy size={14} fill="#D6A62E" />Featured game</p><h2 className="font-display text-[clamp(2rem,4vw,3.8rem)] font-black leading-none">Pick your challenge.</h2></div><p className="max-w-sm text-right text-sm leading-relaxed text-[#526174] max-sm:text-left">A few minutes between sets, a friendly face-off, or a serious test of band knowledge.</p></div><article className="mx-auto grid max-w-[1400px] overflow-hidden rounded-[2px] border border-[#06182B]/[.08] bg-white shadow-[0_18px_45px_rgba(6,24,43,.1)] md:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]"><Link to="/name-that-tune" className="group relative block aspect-[4/3] min-h-0 overflow-hidden bg-[#06182B] md:aspect-auto md:min-h-[clamp(280px,18vw,360px)]"><img src="/images/home/games/name-that-tune.png" alt="Name That Marching Band Tune" className="size-full object-cover transition duration-700 group-hover:scale-[1.03]" /><div className="absolute inset-0 bg-gradient-to-t from-[#06182B]/75 via-transparent to-transparent" /><div className="absolute bottom-6 left-6 sm:bottom-8 sm:left-8"><p className="font-display text-[clamp(2rem,3.5vw,3.6rem)] font-black uppercase italic leading-none text-white">Name That Marching Band Tune</p><p className="mt-2 text-[10px] font-bold uppercase tracking-[.16em] text-[#F2C550]">Music challenge</p></div></Link><div className="flex flex-col justify-center p-[clamp(1.5rem,3vw,3.5rem)]"><p className="text-[10px] font-black uppercase tracking-[.16em] text-[#B6292E]">Featured game</p><h3 className="mt-3 font-display text-[clamp(2rem,3.5vw,4rem)] font-black leading-[.86]">Can you name the marching band tune?</h3><p className="mt-5 max-w-lg text-[clamp(.9rem,1.1vw,1.05rem)] leading-relaxed text-[#526174]">Listen to a short marching band tune and pick the correct song from four choices. How many can you guess?</p><div className="mt-5 flex flex-wrap gap-x-6 gap-y-2 text-[9px] font-bold uppercase tracking-[.08em] text-[#667386]"><span>◷ 2–5 min</span><span>▥ all ages</span><span><Users className="mr-1 inline" size={12} />1+ players</span></div><Link to="/name-that-tune" className="mt-7 inline-flex min-h-11 w-fit items-center gap-8 bg-[#06182B] px-6 text-[10px] font-black uppercase text-white transition hover:bg-[#B6292E]">Play now <ArrowRight size={15} /></Link></div></article><div className="mt-[clamp(2.5rem,5vw,5rem)] grid auto-rows-fr gap-[clamp(1rem,1.8vw,1.75rem)] sm:grid-cols-2 lg:grid-cols-3">{games.map(game => <GameCard key={game.title} game={game} />)}</div></div></main>

    <PartnersSection />
  </div>;
}
